# Generated by Django 5.2.1 on 2025-10-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0005_valecaja_tipo_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='valecaja',
            name='status',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('comprobado', 'Comprobado')], default='pendiente', max_length=20),
        ),
    ]
