# Generated by Django 5.2.1 on 2025-10-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0006_valecaja_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valecaja',
            name='status',
            field=models.CharField(choices=[('pendiente', 'No'), ('comprobado', 'Si')], default='pendiente', max_length=20),
        ),
    ]
