# Generated by Django 5.2.1 on 2025-10-24 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0008_alter_valecaja_status'),
        ('empleados', '0005_incidencia_importe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valecaja',
            name='recibido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.empleado'),
        ),
    ]
