# Generated by Django 5.2.8 on 2026-05-13 01:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0009_alter_valecaja_recibido_por'),
        ('empresas', '0011_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='fondeocajachica',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fondeos_caja_chica', to='empresas.cuentabancaria'),
        ),
    ]
