# Generated by Django 5.2.8 on 2026-08-11 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja_chica', '0010_fondeocajachica_cuenta_bancaria'),
        ('empresas', '0028_empresa_precio_toalla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fondeocajachica',
            name='cuenta_bancaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fondeos_caja_chica', to='empresas.cuentabancaria'),
        ),
    ]
