# Generated by Django 5.2.8 on 2026-09-15 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0033_alter_empresa_segmento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IngresoEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('colegiatura', 'Colegiatura'), ('inscripcion', 'Inscripción'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('archivo_origen', models.CharField(blank=True, help_text='Nombre del archivo Excel del que se importó, para rastrear el origen.', max_length=255, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos_escuela', to='empresas.empresa')),
                ('importado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
