# Generated by Django 5.2.8 on 2026-09-16 04:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingresoescuela',
            name='alumno',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ingresoescuela',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12),
        ),
        migrations.AddField(
            model_name='ingresoescuela',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='ingresoescuela',
            name='matricula',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ingresoescuela',
            name='origen',
            field=models.CharField(blank=True, choices=[('cobranza', 'Reporte de Cobranza'), ('fiserv', 'Plataforma Academic (Fiserv)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ingresoescuela',
            name='porcentaje_comision_aplicado',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de comision aplicado a este registro en el momento de importarlo.', max_digits=5, null=True),
        ),
    ]
