# Generated by Django 5.2.8 on 2026-09-18 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_alter_empresa_segmento'),
        ('escuelas', '0002_ingresoescuela_alumno_ingresoescuela_comision_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubspot_deal_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre_contacto', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('nivel_de_interes', models.CharField(blank=True, max_length=100, null=True)),
                ('mensaje', models.TextField(blank=True, null=True)),
                ('etapa', models.CharField(choices=[('prospecto', 'Prospecto'), ('contacto', 'Contacto'), ('visita_agendada', 'Visita agendada'), ('visita_realizada', 'Visita realizada'), ('solicitud', 'Solicitud'), ('inscrito', 'Inscrito')], default='prospecto', max_length=30)),
                ('fecha_creacion_hubspot', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_recibido', models.DateTimeField(auto_now_add=True)),
                ('payload_crudo', models.JSONField(blank=True, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_admision', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
