# Generated by Django 5.2.8 on 2026-09-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_alter_empresa_segmento'),
        ('escuelas', '0003_solicitudadmision'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20)),
                ('nombre', models.CharField(max_length=255)),
                ('nivel', models.CharField(blank=True, choices=[('preescolar', 'Preescolar'), ('primaria', 'Primaria')], max_length=20, null=True)),
                ('grado', models.CharField(blank=True, max_length=50, null=True)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('turno', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_alta', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ultimo_visto', models.DateField(blank=True, null=True)),
                ('fecha_baja_detectada', models.DateField(blank=True, null=True)),
                ('fecha_importacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumnos', to='empresas.empresa')),
            ],
            options={
                'ordering': ['nivel', 'grado', 'grupo', 'nombre'],
                'unique_together': {('empresa', 'matricula')},
            },
        ),
    ]
