# Generated by Django 5.2.8 on 2026-09-21 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_alter_empresa_segmento'),
        ('escuelas', '0004_alumno'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteraVencida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(db_index=True, max_length=20)),
                ('nombre_alumno', models.CharField(max_length=255)),
                ('grupo', models.CharField(blank=True, max_length=20, null=True)),
                ('concepto', models.CharField(max_length=255)),
                ('categoria', models.CharField(choices=[('colegiatura', 'Colegiatura'), ('inscripcion', 'Inscripción'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_importacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartera_vencida', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-monto'],
            },
        ),
    ]
