# Generated by Django 5.2.8 on 2026-09-22 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0033_alter_empresa_segmento'),
        ('escuelas', '0005_carteravencida'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoIngresoEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveIntegerField()),
                ('categoria', models.CharField(choices=[('colegiatura', 'Colegiatura'), ('inscripcion', 'Inscripción'), ('otro', 'Otro')], max_length=20)),
                ('monto_presupuestado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos_ingreso_escuela', to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'anio', 'mes', 'categoria')},
            },
        ),
    ]
