# Generated by Django 5.2.8 on 2026-09-23 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0006_presupuestoingresoescuela'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carteravencida',
            options={'ordering': ['-fecha_corte', '-monto']},
        ),
        migrations.AddField(
            model_name='carteravencida',
            name='fecha_corte',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
