# Generated by Django 5.2.8 on 2026-09-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuelas', '0007_alter_carteravencida_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carteravencida',
            name='fecha_corte',
            field=models.DateField(db_index=True),
        ),
    ]
