# Generated by Django 5.2.1 on 2025-09-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0018_areacomun_cantidad_areas_alter_areacomun_tipo_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='tipo_area',
            field=models.CharField(choices=[('Modulo', 'modulo'), ('Stand', 'stand'), ('Espacio', 'superficie'), ('Isla', 'isla'), ('Cajon', 'cajon'), ('Area', 'area'), ('Otro', 'otro')], default='Modulo', max_length=20),
        ),
    ]
