# Generated by Django 5.2.1 on 2025-11-10 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0019_alter_areacomun_tipo_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='es_cuota_anual',
            field=models.BooleanField(default=False, verbose_name='¿Cuota anual?'),
        ),
    ]
