# Generated by Django 5.2.8 on 2026-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0020_areacomun_es_cuota_anual'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='es_cuota_anual',
            field=models.BooleanField(default=False, verbose_name='¿Cuota global? un solo pago'),
        ),
    ]
