# Generated by Django 5.2.8 on 2026-07-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0021_alter_areacomun_es_cuota_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
