# Generated by Django 5.2.8 on 2026-08-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0022_areacomun_referencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='es_cuota_variable',
            field=models.BooleanField(default=False, help_text='Si está activo, el importe NO se captura aquí -- se determina cada vez que el usuario factura manualmente esta área. Esta área nunca se incluye en la facturación mensual automática.', verbose_name='¿Cuota variable?'),
        ),
    ]
