# Generated by Django 5.2.8 on 2026-09-05 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0023_areacomun_es_cuota_variable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='clausulas_especiales',
            field=models.TextField(blank=True, help_text='Exclusividad de zona, restricciones de uso, u otras condiciones especiales del contrato.', null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='contrato_pdf',
            field=models.FileField(blank=True, help_text='Documento del contrato de arrendamiento firmado.', null=True, upload_to='contratos_areas/'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='estatus_deposito',
            field=models.CharField(blank=True, choices=[('retenido', 'Retenido'), ('devuelto', 'Devuelto'), ('aplicado_danos', 'Aplicado a daños')], default='retenido', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='fecha_ultimo_incremento',
            field=models.DateField(blank=True, help_text='Última vez que se aplicó un incremento a la cuota de esta área.', null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='penalizacion_atraso_porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% de recargo por atraso en el pago, según contrato.', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='plazo_forzoso_meses',
            field=models.PositiveIntegerField(blank=True, help_text='Meses durante los cuales el arrendatario NO puede rescindir sin penalización.', null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='porcentaje_incremento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='% a aplicar cada aniversario del contrato (si el tipo es porcentaje fijo).', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='renovacion_automatica',
            field=models.BooleanField(default=False, verbose_name='¿Renovación automática al vencer?'),
        ),
        migrations.AddField(
            model_name='areacomun',
            name='tipo_incremento',
            field=models.CharField(choices=[('ninguno', 'Sin incremento automático'), ('porcentaje_fijo', 'Porcentaje fijo'), ('inpc', 'Indexado a INPC')], default='ninguno', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialIncrementoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_aplicacion', models.DateField(auto_now_add=True)),
                ('cuota_anterior', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_nueva', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('aplicado_por', models.ForeignKey(blank=True, help_text='Vacío si el incremento lo aplicó el comando automático.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_incrementos', to='areas.areacomun')),
            ],
            options={
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
