# Generated by Django 5.2.8 on 2026-09-09 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0024_areacomun_clausulas_especiales_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacomun',
            name='clausulas_especiales',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='contrato_pdf',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='estatus_deposito',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='fecha_ultimo_incremento',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='penalizacion_atraso_porcentaje',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='plazo_forzoso_meses',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='porcentaje_incremento',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='renovacion_automatica',
        ),
        migrations.RemoveField(
            model_name='areacomun',
            name='tipo_incremento',
        ),
        migrations.DeleteModel(
            name='HistorialIncrementoArea',
        ),
    ]
