# Generated by Django 5.2.8 on 2026-09-10 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0025_remove_areacomun_clausulas_especiales_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacomun',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='status',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('disponible', 'Disponible'), ('mantenimiento', 'Mantenimiento'), ('en_juicio', 'En juicio')], default='disponible', max_length=20),
        ),
        migrations.AlterField(
            model_name='areacomun',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
