# Generated by Django 5.2.8 on 2026-09-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0026_alter_areacomun_cuota_alter_areacomun_observaciones_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='areacomun',
            name='periodicidad_facturacion',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', help_text='Se sincroniza automáticamente desde el contrato vigente -- determina cada cuánto se factura esta área.', max_length=20),
        ),
    ]
