# Generated by Django 5.2.8 on 2026-01-28 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0012_localcomercial_es_cuota_anual'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='tipo_propiedad',
            field=models.CharField(choices=[('local', 'Local Comercial'), ('casa', 'Casa'), ('departamento', 'Departamento'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], default='local', max_length=20),
        ),
    ]
