# Generated by Django 5.2.8 on 2026-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0013_localcomercial_tipo_propiedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='tipo_propiedad',
            field=models.CharField(choices=[('local', 'Local Comercial'), ('casa', 'Casa'), ('departamento', 'Departamento'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], max_length=20),
        ),
    ]
