# Generated by Django 5.2.8 on 2026-07-24 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0014_alter_localcomercial_tipo_propiedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
