# Generated by Django 5.2.8 on 2026-07-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0015_localcomercial_referencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='proindiviso',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Porcentaje de proindiviso de la propiedad (%)', max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
