# Generated by Django 5.2.8 on 2026-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0016_localcomercial_proindiviso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='status',
            field=models.CharField(choices=[('ocupado', 'Ocupado'), ('disponible', 'Disponible'), ('mantenimiento', 'Remodelacion'), ('legal', 'Juicio'), ('venta', 'Venta')], default='ocupado', max_length=20),
        ),
        migrations.AlterField(
            model_name='localcomercial',
            name='tipo_propiedad',
            field=models.CharField(choices=[('local', 'Local'), ('casa', 'Casa'), ('departamento', 'Departamento'), ('oficina', 'Oficina'), ('bodega', 'Bodega'), ('terreno', 'Terreno')], max_length=20),
        ),
    ]
