# Generated by Django 5.2.8 on 2026-07-30 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locales', '0017_alter_localcomercial_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcomercial',
            name='status',
            field=models.CharField(choices=[('ocupado', 'Ocup.'), ('disponible', 'Disp.'), ('mantenimiento', 'en Remod.'), ('legal', 'en Juicio'), ('venta', 'en Venta')], default='ocupado', max_length=20),
        ),
    ]
