# Generated by Django 5.2.8 on 2026-08-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0053_factura_locales_incluidos_grupofacturacion'),
        ('locales', '0018_alter_localcomercial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='grupo_facturacion',
            field=models.ForeignKey(blank=True, help_text='Si este local se factura junto con otros del mismo cliente, selecciona el grupo aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locales', to='facturacion.grupofacturacion'),
        ),
    ]
