# Generated by Django 5.2.8 on 2026-08-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0054_alter_factura_observaciones_poolvacancia_and_more'),
        ('locales', '0019_localcomercial_grupo_facturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='localcomercial',
            name='pool_vacancia',
            field=models.ForeignKey(blank=True, help_text='Si este local se queda SIN cliente, se factura automáticamente su cuota al cliente que cubre este pool.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locales_elegibles', to='facturacion.poolvacancia'),
        ),
    ]
