# Generated by Django 5.2.8 on 2026-07-04 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0009_cliente_referencia_pago'),
        ('empresas', '0014_alter_empresa_cuenta_bancaria'),
        ('facturacion', '0049_alter_facturaotrosingresos_observaciones'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='estados_cuenta_pdf/')),
                ('banco_detectado', models.CharField(blank=True, max_length=50)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('saldo_inicial', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('total_abonos', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('estado', models.CharField(choices=[('procesando', 'Procesando'), ('listo', 'Listo para revisar'), ('aplicado', 'Aplicado'), ('error', 'Error')], default='procesando', max_length=20)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_estado_cuenta', to='empresas.empresa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sesión de estado de cuenta',
                'verbose_name_plural': 'Sesiones de estado de cuenta',
                'ordering': ['-fecha_registro'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.TextField()),
                ('referencia', models.CharField(blank=True, max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confianza_match', models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja'), ('ninguna', 'Sin match')], default='ninguna', max_length=20)),
                ('razon_match', models.CharField(blank=True, max_length=255)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de asignar'), ('asignado_factura', 'Asignado a factura existente'), ('factura_nueva', 'Factura nueva creada'), ('ignorado', 'Ignorado')], default='pendiente', max_length=20)),
                ('cliente_detectado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_estado_cuenta', to='clientes.cliente')),
                ('factura_otros_ingresos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.facturaotrosingresos')),
                ('pago_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimiento_estado_cuenta', to='facturacion.pago')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='cobros_estado_cuenta.sesionestadocuenta')),
            ],
            options={
                'ordering': ['fecha', 'monto'],
            },
        ),
    ]
