# Generated by Django 5.2.8 on 2026-07-24 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0022_areacomun_referencia_pago'),
        ('cobros_estado_cuenta', '0001_initial'),
        ('locales', '0015_localcomercial_referencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='propiedad_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_estado_cuenta', to='areas.areacomun'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='propiedad_local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_estado_cuenta', to='locales.localcomercial'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='propiedad_tipo',
            field=models.CharField(blank=True, choices=[('local', 'Local Comercial'), ('area', 'Área Común')], max_length=10, null=True),
        ),
    ]
