# Generated by Django 5.2.8 on 2026-07-24 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_cliente_referencia_pago'),
        ('cobros_estado_cuenta', '0002_movimientoestadocuenta_propiedad_area_and_more'),
        ('facturacion', '0049_alter_facturaotrosingresos_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='cliente_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_asignados_edc', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='monto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.CreateModel(
            name='AplicacionMovimientoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('cobro_otros_ingresos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.cobrootrosingresos')),
                ('factura_cuota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura')),
                ('factura_otros', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.facturaotrosingresos')),
                ('movimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='cobros_estado_cuenta.movimientoestadocuenta')),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pago')),
            ],
            options={
                'ordering': ['fecha_aplicacion'],
            },
        ),
    ]
