# Generated by Django 5.2.8 on 2026-07-25 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros_estado_cuenta', '0003_movimientoestadocuenta_cliente_asignado_and_more'),
        ('empresas', '0020_alter_empresa_radio_permitido_metros'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovimientoInversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo', models.CharField(choices=[('aportacion', 'Aportación (dinero que entra a la inversión)'), ('rendimiento', 'Rendimiento generado'), ('retiro', 'Retiro de la inversión (regresa a la cuenta)')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_inversion', to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('movimiento_estado_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cobros_estado_cuenta.movimientoestadocuenta')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inversión',
                'verbose_name_plural': 'Movimientos de inversión',
                'ordering': ['-fecha'],
            },
        ),
    ]
