# Generated by Django 5.2.8 on 2026-07-25 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros_estado_cuenta', '0004_movimientoinversion'),
        ('gastos', '0005_gasto_folio_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinversion',
            name='gasto_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.gasto'),
        ),
        migrations.AddField(
            model_name='movimientoinversion',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
