# Generated by Django 5.2.8 on 2026-07-25 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cobros_estado_cuenta', '0005_movimientoinversion_gasto_generado_and_more'),
        ('empresas', '0020_alter_empresa_radio_permitido_metros'),
        ('gastos', '0005_gasto_folio_comprobante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TraspasoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('concepto', models.CharField(choices=[('aportacion_inversion', 'Aportación a inversión'), ('rendimiento_inversion', 'Rendimiento de inversión'), ('retiro_inversion', 'Retiro de inversión'), ('otro', 'Otro traspaso')], default='otro', max_length=30)),
                ('retencion_isr', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_entrantes', to='empresas.cuentabancaria')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traspasos_salientes', to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('gasto_generado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.gasto')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traspaso entre cuentas',
                'verbose_name_plural': 'Traspasos entre cuentas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.DeleteModel(
            name='MovimientoInversion',
        ),
    ]
