# Generated by Django 5.2.8 on 2026-07-25 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cobros_estado_cuenta', '0006_traspasocuenta_delete_movimientoinversion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TraspasoCuenta',
        ),
    ]
