# Generated by Django 5.2.8 on 2026-08-17 04:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0011_cliente_objeto_impuesto'),
        ('empresas', '0028_empresa_precio_toalla'),
        ('facturacion', '0057_factura_monto_base_factura_monto_iva_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpedienteCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etapa', models.CharField(choices=[('recordatorio', 'Recordatorio amistoso'), ('llamada', 'Llamada de seguimiento'), ('carta_intencion', 'Carta de intención'), ('carta_extrajudicial', 'Carta extrajudicial'), ('plan_pago', 'Plan de pago'), ('juridico', 'Turnado a jurídico'), ('cerrado', 'Cerrado / Resuelto')], default='recordatorio', max_length=25)),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=10)),
                ('fecha_apertura', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('motivo_cierre', models.CharField(blank=True, max_length=255, null=True)),
                ('notas_generales', models.TextField(blank=True, null=True)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_asignados', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_cobranza', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expedientes_cobranza', to='empresas.empresa')),
            ],
            options={
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='GestionCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_gestion', models.CharField(choices=[('llamada', 'Llamada telefónica'), ('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Correo electrónico'), ('carta_extrajudicial', 'Carta extrajudicial'), ('visita', 'Visita presencial'), ('nota', 'Nota interna')], max_length=25)),
                ('resultado', models.CharField(choices=[('promesa_pago', 'Promesa de pago'), ('no_contesto', 'No contestó'), ('se_nego', 'Se negó a pagar'), ('numero_equivocado', 'Número/dato equivocado'), ('ya_pago', 'Ya había pagado'), ('pendiente_respuesta', 'Pendiente de respuesta'), ('otro', 'Otro')], default='pendiente_respuesta', max_length=25)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('mensaje_enviado', models.TextField(blank=True, null=True)),
                ('envio_exitoso', models.BooleanField(blank=True, null=True)),
                ('envio_id_externo', models.CharField(blank=True, max_length=100, null=True)),
                ('envio_error', models.CharField(blank=True, max_length=255, null=True)),
                ('proxima_accion_fecha', models.DateField(blank=True, null=True)),
                ('proxima_accion_descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('proxima_accion_completada', models.BooleanField(default=False)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='gestion_cobranza.expedientecobranza')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='PlanDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_acuerdo', models.DateField(auto_now_add=True)),
                ('monto_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numero_parcialidades', models.PositiveIntegerField()),
                ('estatus', models.CharField(choices=[('activo', 'Activo'), ('cumplido', 'Cumplido'), ('incumplido', 'Incumplido'), ('cancelado', 'Cancelado')], default='activo', max_length=15)),
                ('notas', models.TextField(blank=True, null=True)),
                ('comprobante_acuerdo', models.FileField(blank=True, null=True, upload_to='cobranza/planes_pago/')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_pago', to='gestion_cobranza.expedientecobranza')),
            ],
            options={
                'ordering': ['-fecha_acuerdo'],
            },
        ),
        migrations.CreateModel(
            name='ParcialidadPlanPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('vencida', 'Vencida')], default='pendiente', max_length=15)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.pago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcialidades', to='gestion_cobranza.plandepago')),
            ],
            options={
                'ordering': ['plan', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='PlantillaCobranza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('email', 'Correo electrónico'), ('carta_extrajudicial', 'Carta extrajudicial (PDF)')], max_length=25)),
                ('nombre', models.CharField(help_text="Nombre interno para identificarla, ej. 'Recordatorio 5 días'.", max_length=100)),
                ('etapa_sugerida', models.CharField(blank=True, choices=[('recordatorio', 'Recordatorio amistoso'), ('llamada', 'Llamada de seguimiento'), ('carta_intencion', 'Carta de intención'), ('carta_extrajudicial', 'Carta extrajudicial'), ('plan_pago', 'Plan de pago'), ('juridico', 'Turnado a jurídico'), ('cerrado', 'Cerrado / Resuelto')], help_text='En qué etapa del pipeline se sugiere usar esta plantilla (opcional).', max_length=25, null=True)),
                ('asunto', models.CharField(blank=True, help_text='Solo aplica para correo.', max_length=200, null=True)),
                ('cuerpo', models.TextField(help_text='Usa placeholders: {nombre_cliente}, {monto_vencido}, {dias_atraso}, {folios_pendientes}, {nombre_empresa}, {fecha_hoy}.')),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantillas_cobranza', to='empresas.empresa')),
            ],
            options={
                'ordering': ['canal', 'nombre'],
            },
        ),
        migrations.AddConstraint(
            model_name='expedientecobranza',
            constraint=models.UniqueConstraint(condition=models.Q(('estatus', 'activo')), fields=('empresa', 'cliente'), name='unico_expediente_activo_por_cliente'),
        ),
        migrations.AlterUniqueTogether(
            name='parcialidadplanpago',
            unique_together={('plan', 'numero')},
        ),
    ]
