# Generated by Django 5.2.8 on 2026-08-19 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_alter_ubicacionenvivo_empleado'),
        ('gestion_cobranza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientecobranza',
            name='monto_al_cierre',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Saldo vencido que tenía el expediente al momento de cerrarse.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='expedientecobranza',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes_asignados', to='empleados.empleado'),
        ),
    ]
