# Generated by Django 5.2.8 on 2026-08-22 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranza', '0002_expedientecobranza_monto_al_cierre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantillacobranza',
            name='cuerpo',
            field=models.TextField(help_text='Usa placeholders: {nombre_cliente}, {monto_vencido}, {dias_atraso}, {folios_pendientes}, {propiedades},{nombre_empresa}, {fecha_hoy}.'),
        ),
    ]
