# Generated by Django 5.2.8 on 2026-08-22 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranza', '0003_alter_plantillacobranza_cuerpo'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantillacobranza',
            name='content_sid',
            field=models.CharField(blank=True, help_text='Solo para WhatsApp -- el Content SID (empieza con HX) de tu plantilla ya aprobada en Twilio.', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plantillacobranza',
            name='orden_variables',
            field=models.CharField(blank=True, help_text='Solo para WhatsApp con content_sid -- lista los placeholders en el orden exacto en que aparecen en tu plantilla de Twilio, separados por coma. Ej: nombre_cliente,monto_vencido,dias_atraso -- el primero se manda como variable 1, el segundo como variable 2, etc.', max_length=300, null=True),
        ),
    ]
