# Generated by Django 5.2.8 on 2026-08-23 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_cobranza', '0004_plantillacobranza_content_sid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gestioncobranza',
            name='envio_error',
            field=models.TextField(blank=True, null=True),
        ),
    ]
