# Generated by Django 5.2.8 on 2026-08-15 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0013_alter_ubicacionenvivo_empleado'),
        ('empresas', '0028_empresa_precio_toalla'),
        ('gastos', '0009_grupogasto_es_exento_iva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DispersionNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField(blank=True, help_text='Se autocompleta con la fecha de pago de los XML al subirlos, pero puedes ajustarla.', null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('borrador', 'Borrador -- en revisión'), ('confirmado', 'Confirmado -- ya generó los gastos')], default='borrador', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.CharField(blank=True, max_length=255, null=True)),
                ('cuenta_bancaria', models.ForeignKey(help_text='Cuenta desde la que se dispersó la nómina -- el XML no la trae, se indica aquí.', on_delete=django.db.models.deletion.PROTECT, related_name='dispersiones_nomina', to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispersiones_nomina', to='empresas.empresa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ReciboNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo_xml', models.FileField(upload_to='nomina/xml/')),
                ('uuid_fiscal', models.CharField(blank=True, db_index=True, max_length=36, null=True)),
                ('rfc_receptor', models.CharField(blank=True, max_length=13, null=True)),
                ('nombre_receptor', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('periodo_inicio', models.DateField(blank=True, null=True)),
                ('periodo_fin', models.DateField(blank=True, null=True)),
                ('total_percepciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_deducciones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('neto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estatus', models.CharField(choices=[('ok', 'Encontrado — listo'), ('sin_match', 'RFC no encontrado — requiere asignación manual'), ('duplicado', 'Ya se había procesado este folio fiscal antes'), ('error', 'Error al leer el XML')], default='sin_match', max_length=20)),
                ('error_detalle', models.CharField(blank=True, max_length=255, null=True)),
                ('dispersion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='nomina.dispersionnomina')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibos_nomina', to='empleados.empleado')),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recibo_nomina', to='gastos.gasto')),
            ],
            options={
                'ordering': ['nombre_receptor'],
            },
        ),
    ]
