# Generated by Django 5.2.8 on 2026-08-15 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibonomina',
            name='total_otros_pagos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Ej. Subsidio para el Empleo -- se le entrega al trabajador aunque no sea una percepción.', max_digits=12),
        ),
    ]
