# Generated by Django 5.2.8 on 2026-08-21 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0031_empresa_absorber_comision_stripe'),
        ('gastos', '0010_gasto_monto_base_gasto_monto_iva'),
        ('nomina', '0002_recibonomina_total_otros_pagos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('percepcion', 'Percepción'), ('deduccion', 'Deducción'), ('otro_pago', 'Otro Pago')], max_length=15)),
                ('clave', models.CharField(blank=True, help_text="Clave del catalogo SAT, ej. '022' (Vacaciones).", max_length=20, null=True)),
                ('concepto', models.CharField(help_text="Texto descriptivo tal como viene en el XML, ej. 'Vacaciones'.", max_length=200)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='concepto_nomina', to='gastos.gasto')),
                ('recibo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='nomina.recibonomina')),
            ],
            options={
                'ordering': ['tipo', 'concepto'],
            },
        ),
        migrations.CreateModel(
            name='MapeoConceptoNomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concepto_xml', models.CharField(help_text="Texto EXACTO del concepto tal como aparece en el XML (ej. 'ISR', 'Seguridad Social').", max_length=200)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapeos_concepto_nomina', to='empresas.empresa')),
                ('tipo_gasto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapeos_nomina', to='gastos.tipogasto')),
            ],
            options={
                'unique_together': {('empresa', 'concepto_xml')},
            },
        ),
    ]
