# Generated by Django 5.2.8 on 2026-08-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_conceptonomina_mapeoconceptonomina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conceptonomina',
            name='importe',
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='importe_exento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='conceptonomina',
            name='importe_gravado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.DeleteModel(
            name='MapeoConceptoNomina',
        ),
    ]
