# Generated by Django 5.2.8 on 2026-08-04 22:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0023_empresa_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de cobro'), ('cobrado', 'Cobrado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('monto', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('fecha_generado', models.DateTimeField(auto_now_add=True)),
                ('fecha_cobro', models.DateTimeField(blank=True, null=True)),
                ('cobrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_sanitario', to='empresas.empresa')),
                ('generado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_generado'],
            },
        ),
    ]
