# Generated by Django 5.2.8 on 2026-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usosanitario',
            name='codigo',
            field=models.CharField(db_index=True, max_length=10),
        ),
    ]
