# Generated by Django 5.2.8 on 2026-08-05 00:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_empresa_usa_boletos_fisicos_sanitario'),
        ('sanitarios', '0002_alter_usosanitario_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CasetaOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej. 'Caseta Principal', 'Estacionamiento Sur'", max_length=100)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='casetas_sanitario', to='empresas.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='usosanitario',
            name='caseta',
            field=models.ForeignKey(blank=True, help_text='Si el uso se registró desde una caseta compartida (sin login), queda aquí en vez de en generado_por/cobrado_por.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='sanitarios.casetaoperador'),
        ),
    ]
