# Generated by Django 5.2.8 on 2026-08-05 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_empresa_usa_boletos_fisicos_sanitario'),
        ('facturacion', '0052_tipootroingreso_cuenta_contable_and_more'),
        ('sanitarios', '0003_casetaoperador_usosanitario_caseta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('total_cobrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('cerrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cortes_sanitario', to='empresas.empresa')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.facturaotrosingresos')),
            ],
            options={
                'unique_together': {('empresa', 'fecha')},
            },
        ),
    ]
