# Generated by Django 5.2.8 on 2026-08-06 00:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_empresa_usa_boletos_fisicos_sanitario'),
        ('sanitarios', '0004_cortesanitario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoletoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('usado', 'Usado'), ('cancelado', 'Cancelado')], default='disponible', max_length=20)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('cargado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boletos_fisicos', to='empresas.empresa')),
                ('uso', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boleto_consumido', to='sanitarios.usosanitario')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
    ]
