# Generated by Django 5.2.8 on 2026-08-07 22:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_empresa_usa_boletos_fisicos_sanitario'),
        ('locales', '0019_localcomercial_grupo_facturacion'),
        ('sanitarios', '0005_boletofisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='GafeteAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('nombre_titular', models.CharField(blank=True, max_length=150, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gafetes_acceso', to='empresas.empresa')),
                ('local', models.ForeignKey(blank=True, help_text='Local al que pertenece este gafete, si aplica.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gafetes_acceso', to='locales.localcomercial')),
            ],
            options={
                'ordering': ['numero'],
                'unique_together': {('empresa', 'numero')},
            },
        ),
    ]
