# Generated by Django 5.2.8 on 2026-08-07 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitarios', '0006_gafeteacceso'),
    ]

    operations = [
        migrations.AddField(
            model_name='usosanitario',
            name='gafete',
            field=models.ForeignKey(blank=True, help_text='Si el uso fue con gafete de acceso gratuito, se registra aquí.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usos', to='sanitarios.gafeteacceso'),
        ),
    ]
