# Generated by Django 5.2.8 on 2026-08-07 23:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0022_areacomun_referencia_pago'),
        ('locales', '0019_localcomercial_grupo_facturacion'),
        ('sanitarios', '0007_usosanitario_gafete'),
    ]

    operations = [
        migrations.AddField(
            model_name='gafeteacceso',
            name='area_comun',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gafetes_acceso', to='areas.areacomun'),
        ),
        migrations.AlterField(
            model_name='gafeteacceso',
            name='local',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gafetes_acceso', to='locales.localcomercial'),
        ),
        migrations.AlterField(
            model_name='gafeteacceso',
            name='nombre_titular',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='gafeteacceso',
            name='numero',
            field=models.CharField(editable=False, max_length=20),
        ),
    ]
