# Generated by Django 5.2.8 on 2026-08-07 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sanitarios', '0008_gafeteacceso_area_comun_alter_gafeteacceso_local_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usosanitario',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente de cobro'), ('cobrado', 'Cobrado'), ('gratis', 'Gratis (gafete)'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20),
        ),
    ]
