# Generated by Django 5.2.8 on 2026-08-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0027_empresa_precio_papel_and_more'),
        ('sanitarios', '0009_alter_usosanitario_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='boletofisico',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='boletofisico',
            name='tipo',
            field=models.CharField(choices=[('sanitario', 'Uso de Sanitario'), ('papel', 'Venta de Papel')], default='sanitario', max_length=20),
        ),
        migrations.AddField(
            model_name='usosanitario',
            name='tipo',
            field=models.CharField(choices=[('sanitario', 'Uso de Sanitario'), ('papel', 'Venta de Papel')], default='sanitario', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='boletofisico',
            unique_together={('empresa', 'tipo', 'codigo')},
        ),
    ]
