# Generated by Django 5.2.8 on 2026-08-08 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0027_empresa_precio_papel_and_more'),
        ('sanitarios', '0010_alter_boletofisico_unique_together_boletofisico_tipo_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cortesanitario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cortesanitario',
            name='tipo',
            field=models.CharField(choices=[('sanitario', 'Uso de Sanitario'), ('papel', 'Venta de Papel')], default='sanitario', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cortesanitario',
            unique_together={('empresa', 'tipo', 'fecha')},
        ),
    ]
