# Generated by Django 5.2.8 on 2026-08-08 01:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_empresa_precio_toalla'),
        ('sanitarios', '0011_alter_cortesanitario_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usosanitario',
            name='tipo',
            field=models.CharField(choices=[('sanitario', 'Uso de Sanitario'), ('papel', 'Venta de Papel'), ('toalla', 'Venta de Toalla Sanitaria')], default='sanitario', max_length=20),
        ),
        migrations.CreateModel(
            name='LoteToallas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50)),
                ('cantidad_inicial', models.PositiveIntegerField()),
                ('cantidad_disponible', models.PositiveIntegerField()),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes_toallas', to='empresas.empresa')),
                ('recibido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_recepcion'],
            },
        ),
        migrations.AddField(
            model_name='usosanitario',
            name='lote_toallas',
            field=models.ForeignKey(blank=True, help_text="Solo aplica cuando tipo='toalla' -- de qué lote salió esta venta.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='sanitarios.lotetoallas'),
        ),
    ]
