# Generated by Django 5.2.8 on 2026-08-08 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_empresa_precio_toalla'),
        ('sanitarios', '0012_alter_usosanitario_tipo_lotetoallas_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cortesanitario',
            unique_together={('empresa', 'fecha')},
        ),
        migrations.RemoveField(
            model_name='cortesanitario',
            name='tipo',
        ),
    ]
