# Generated by Django 5.2.8 on 2026-08-08 07:15

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_alter_ubicacionenvivo_empleado'),
        ('sanitarios', '0013_alter_cortesanitario_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cortesanitario',
            options={'ordering': ['-fecha_hora_fin']},
        ),
        migrations.AlterUniqueTogether(
            name='cortesanitario',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='cortesanitario',
            name='caseta',
            field=models.ForeignKey(blank=True, help_text='Caseta a la que pertenece este corte. Vacío = movimientos generados sin caseta (login directo).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes', to='sanitarios.casetaoperador'),
        ),
        migrations.AddField(
            model_name='cortesanitario',
            name='cerrado_por_empleado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cortes_sanitario_cerrados', to='empleados.empleado'),
        ),
        migrations.AddField(
            model_name='cortesanitario',
            name='fecha_hora_fin',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 8, 7, 15, 28, 401757, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cortesanitario',
            name='fecha_hora_inicio',
            field=models.DateTimeField(default=datetime.datetime(2026, 8, 8, 7, 15, 35, 281701, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cortesanitario',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='cortesanitario',
            name='fecha',
        ),
    ]
