# Generated by Django 5.2.8 on 2026-09-09 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0025_remove_areacomun_clausulas_especiales_and_more'),
        ('clientes', '0011_cliente_objeto_impuesto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_firma', models.DateField(help_text='Fecha en que se firmó el contrato -- puede ser anterior a fecha_inicio.')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cuota', models.DecimalField(decimal_places=2, help_text="Renta fija, o renta base si tipo_renta es 'mixta'. Renta mínima garantizada (o $0) si tipo_renta es 'variable'.", max_digits=10)),
                ('deposito', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estatus', models.CharField(choices=[('vigente', 'Vigente'), ('renovado', 'Renovado (ya existe uno nuevo)'), ('terminado', 'Terminado sin renovar')], default='vigente', max_length=20)),
                ('plazo_forzoso_meses', models.PositiveIntegerField(blank=True, help_text='Meses durante los cuales el arrendatario NO puede rescindir sin penalizacion -- vinculado con fecha_inicio/fecha_fin (captura cualquiera de los 2, el otro se calcula solo).', null=True)),
                ('renovacion_automatica', models.BooleanField(default=False, help_text="Si está activo (junto con tipo_incremento='porcentaje_fijo'), habilita el botón de un clic 'Renovar con % pactado' en Gestión de Contratos.", verbose_name='¿Renovación automática al vencer?')),
                ('tipo_incremento', models.CharField(choices=[('ninguno', 'Sin incremento pactado'), ('porcentaje_fijo', 'Porcentaje fijo'), ('inpc', 'Indexado a INPC')], default='ninguno', max_length=20)),
                ('porcentaje_incremento', models.DecimalField(blank=True, decimal_places=2, help_text='% pactado en el contrato (si el tipo es porcentaje fijo).', max_digits=5, null=True)),
                ('periodicidad_facturacion', models.CharField(choices=[('mensual', 'Mensual'), ('dias', 'Por días (prorrateo)'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20)),
                ('tipo_renta', models.CharField(choices=[('fija', 'Fija'), ('variable', 'Variable (% sobre ventas)'), ('mixta', 'Mixta (renta base + % sobre ventas)')], default='fija', max_length=20)),
                ('porcentaje_ventas', models.DecimalField(blank=True, decimal_places=2, help_text="% sobre ventas netas del arrendatario -- aplica si tipo_renta es 'variable' o 'mixta'.", max_digits=5, null=True)),
                ('incluye_mantenimiento', models.BooleanField(default=False, help_text='Cargo aparte, independiente del tipo de renta -- se puede activar junto con renta fija, variable, o mixta.', verbose_name='¿Incluye cuota de mantenimiento?')),
                ('cuota_mantenimiento', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del cargo de mantenimiento -- aplica si incluye_mantenimiento está activo.', max_digits=10, null=True)),
                ('penalizacion_atraso_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='% de recargo por atraso en el pago, según contrato.', max_digits=5, null=True)),
                ('estatus_deposito', models.CharField(blank=True, choices=[('retenido', 'Retenido'), ('devuelto', 'Devuelto'), ('aplicado_danos', 'Aplicado a daños'), ('aplicado_adeudos', 'Aplicado a rentas')], default='retenido', max_length=20, null=True)),
                ('clausulas_especiales', models.TextField(blank=True, help_text='Exclusividad de zona, restricciones de uso, u otras condiciones especiales.', null=True)),
                ('contrato_pdf', models.FileField(blank=True, help_text='Documento del contrato de arrendamiento firmado -- opcional.', null=True, upload_to='contratos_areas/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='areas.areacomun')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contratos_areas', to='clientes.cliente')),
                ('contrato_anterior', models.ForeignKey(blank=True, help_text='Si este contrato es una renovación de uno anterior, apunta hacia él.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renovaciones', to='arrendamientos.contratoarea')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ReporteVentasContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_inicio', models.DateField()),
                ('periodo_fin', models.DateField()),
                ('monto_ventas', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_aplicado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('renta_variable_calculada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('renta_base_del_periodo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_a_cobrar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_captura', models.DateTimeField(auto_now_add=True)),
                ('capturado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportes_ventas', to='arrendamientos.contratoarea')),
            ],
            options={
                'ordering': ['-periodo_inicio'],
            },
        ),
    ]
