# Generated by Django 5.2.8 on 2026-09-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratoarea',
            name='giro',
            field=models.CharField(blank=True, help_text='Giro comercial del arrendatario -- ej. restaurante, ropa, servicios.', max_length=100, null=True),
        ),
    ]
