# Generated by Django 5.2.8 on 2026-09-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0002_contratoarea_giro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarea',
            name='periodicidad_facturacion',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('semestral', 'Semestral'), ('anual', 'Anual')], default='mensual', max_length=20),
        ),
    ]
