# Generated by Django 5.2.8 on 2026-09-12 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arrendamientos', '0003_alter_contratoarea_periodicidad_facturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratoarea',
            name='estatus',
            field=models.CharField(choices=[('vigente', 'Vigente'), ('renovado', 'Renovado (ya existe uno nuevo)'), ('vencido_ocupado', 'Vencido -- Ocupado (mes a mes)'), ('terminado', 'Terminado sin renovar')], default='vigente', max_length=20),
        ),
    ]
