# Generated by Django 5.2.8 on 2026-07-10 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('traspasos', '0002_saldocuentaperiodo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SaldoCuentaPeriodo',
        ),
    ]
