# Generated by Django 5.2.8 on 2026-07-25 22:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_gasto_folio_comprobante'),
        ('traspasos', '0003_delete_saldocuentaperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='traspasobancario',
            name='es_inversion',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traspasobancario',
            name='gasto_generado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gastos.gasto'),
        ),
        migrations.AddField(
            model_name='traspasobancario',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
