# Generated by Django 5.2.8 on 2026-07-25 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traspasos', '0004_traspasobancario_es_inversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traspasobancario',
            name='tipo_movimiento_inversion',
            field=models.CharField(blank=True, choices=[('incremento', 'Incremento de inversión'), ('rendimiento_liquidacion', 'Rendimiento / Liquidación'), ('retiro_fondeo', 'Retiro para fondeo')], max_length=30, null=True),
        ),
    ]
