# Generated by Django 5.2.8 on 2026-07-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traspasos', '0005_traspasobancario_tipo_movimiento_inversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traspasobancario',
            name='tipo_movimiento_inversion',
            field=models.CharField(blank=True, choices=[('incremento', 'Incremento de inversión'), ('retiro', 'Retiro / Liquidación de inversión')], max_length=30, null=True),
        ),
    ]
