# Generated by Django 5.2.1 on 2025-08-31 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0035_alter_factura_fecha_emision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='fecha_vencimiento',
            field=models.DateField(),
        ),
    ]
