# Generated by Django 5.2.1 on 2025-10-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0036_alter_factura_fecha_vencimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('stripe', 'Stripe'), ('otro', 'Otro')], default='transferencia', max_length=100),
        ),
    ]
