# Generated by Django 5.2.1 on 2025-10-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0037_alter_pago_forma_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cfdi',
        ),
        migrations.RemoveField(
            model_name='facturaotrosingresos',
            name='cfdi',
        ),
        migrations.AddField(
            model_name='factura',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='facturaotrosingresos',
            name='uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
