# Generated by Django 5.2.1 on 2025-10-09 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0038_remove_factura_cfdi_remove_facturaotrosingresos_cfdi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='facturama_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
