# Generated by Django 5.2.1 on 2025-10-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0039_factura_facturama_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaotrosingresos',
            name='facturama_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
