# Generated by Django 5.2.1 on 2025-10-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0040_facturaotrosingresos_facturama_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='tipo_cuota',
            field=models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('renta', 'Renta'), ('deposito', 'Deposito Garantía'), ('extraordinaria', 'Extraordinaria'), ('penalidad', 'Multa'), ('intereses', 'Intereses')], max_length=100),
        ),
    ]
