# Generated by Django 5.2.1 on 2025-11-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_es_plus'),
        ('facturacion', '0041_alter_factura_tipo_cuota'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='facturaotrosingresos',
            unique_together={('folio', 'empresa')},
        ),
    ]
