# Generated by Django 5.2.1 on 2025-11-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0042_alter_facturaotrosingresos_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaotrosingresos',
            name='folio',
            field=models.CharField(max_length=50),
        ),
    ]
