# Generated by Django 5.2.8 on 2025-12-17 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0043_alter_facturaotrosingresos_folio'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='identificado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pago',
            name='factura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='facturacion.factura'),
        ),
    ]
