# Generated by Django 5.2.8 on 2025-12-17 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_es_plus'),
        ('facturacion', '0044_pago_identificado_alter_pago_factura'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa'),
        ),
    ]
