# Generated by Django 5.2.8 on 2026-01-22 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0045_pago_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='factura_global',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_incluidas', to='facturacion.factura'),
        ),
    ]
