# Generated by Django 5.2.8 on 2026-05-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_empresa_cuenta_bancaria'),
        ('facturacion', '0046_factura_factura_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='pago',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.cuentabancaria'),
        ),
    ]
