# Generated by Django 5.2.8 on 2026-05-07 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_empresa_cuenta_bancaria'),
        ('facturacion', '0047_pago_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrootrosingresos',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cobros_oi', to='empresas.cuentabancaria'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='empresas.cuentabancaria'),
        ),
    ]
