# Generated by Django 5.2.8 on 2026-05-10 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0048_cobrootrosingresos_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaotrosingresos',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
