# Generated by Django 5.2.8 on 2026-07-25 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0050_alter_pago_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('stripe', 'Stripe'), ('rendimiento_inversion', 'Rendimiento de Inversión'), ('otro', 'Otro')], default='transferencia', max_length=100),
        ),
    ]
