# Generated by Django 5.2.8 on 2026-07-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_cuentabancaria_cuenta_contable'),
        ('facturacion', '0051_alter_pago_forma_pago'),
        ('gastos', '0007_cargacatalogosesion_cargacatalogofila'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipootroingreso',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_otro_ingreso', to='gastos.cuentacontable'),
        ),
        migrations.CreateModel(
            name='TipoCuotaHomologacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuota', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('renta', 'Renta'), ('deposito', 'Deposito Garantía'), ('extraordinaria', 'Extraordinaria'), ('penalidad', 'Multa'), ('intereses', 'Intereses')], max_length=100)),
                ('cuenta_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gastos.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homologaciones_cuota', to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'tipo_cuota')},
            },
        ),
    ]
