# Generated by Django 5.2.8 on 2026-08-06 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_cliente_referencia_pago'),
        ('empresas', '0026_empresa_usa_boletos_fisicos_sanitario'),
        ('facturacion', '0052_tipootroingreso_cuenta_contable_and_more'),
        ('locales', '0018_alter_localcomercial_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='locales_incluidos',
            field=models.ManyToManyField(blank=True, help_text='Para facturas consolidadas de un grupo: todos los locales que cubre esta factura.', related_name='facturas_grupo', to='locales.localcomercial'),
        ),
        migrations.CreateModel(
            name='GrupoFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text="Ej. 'Tiendas Soriana — Plaza Norte'", max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_facturacion', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_facturacion', to='empresas.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
    ]
