# Generated by Django 5.2.8 on 2026-08-12 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0011_cliente_objeto_impuesto'),
        ('empresas', '0028_empresa_precio_toalla'),
        ('facturacion', '0053_factura_locales_incluidos_grupofacturacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='observaciones',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='PoolVacancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('cliente_cobertura', models.ForeignKey(help_text='Cliente al que se le factura por los locales de este pool que estén vacíos cada mes.', on_delete=django.db.models.deletion.PROTECT, related_name='pools_vacancia_cubiertos', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools_vacancia', to='empresas.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='pool_vacancia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas_generadas', to='facturacion.poolvacancia'),
        ),
    ]
