# Generated by Django 5.2.8 on 2026-08-13 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0022_areacomun_referencia_pago'),
        ('clientes', '0011_cliente_objeto_impuesto'),
        ('empresas', '0028_empresa_precio_toalla'),
        ('facturacion', '0054_alter_factura_observaciones_poolvacancia_and_more'),
        ('locales', '0020_localcomercial_pool_vacancia'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('efectivo', 'Efectivo'), ('stripe', 'Stripe'), ('rendimiento_inversion', 'Rendimiento Inv.'), ('saldo_a_favor', 'Saldo a Favor (pago adelantado)'), ('otro', 'Otro')], default='transferencia', max_length=100),
        ),
        migrations.CreateModel(
            name='SaldoAFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_original', models.DecimalField(decimal_places=2, max_digits=20)),
                ('monto_disponible', models.DecimalField(decimal_places=2, max_digits=20)),
                ('fecha_registro', models.DateField()),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('area_comun', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_a_favor', to='areas.areacomun')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='saldos_a_favor', to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_a_favor', to='empresas.empresa')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldos_a_favor', to='locales.localcomercial')),
                ('origen_pago', models.ForeignKey(blank=True, help_text='El depósito original (sin factura) que dio origen a este saldo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldo_a_favor_generado', to='facturacion.pago')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha_registro'],
            },
        ),
    ]
