# Generated by Django 5.2.8 on 2026-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0055_alter_pago_forma_pago_saldoafavor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cobrootrosingresos',
            name='forma_cobro',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('otro', 'Otro')], default='transferencia', max_length=20),
        ),
        migrations.AlterField(
            model_name='pago',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta'), ('nota_credito', 'Nota de Crédito'), ('deposito', 'Depósito'), ('stripe', 'Stripe'), ('rendimiento_inversion', 'Rendimiento Inv.'), ('saldo_a_favor', 'Saldo a Favor (pago adelantado)'), ('otro', 'Otro')], default='transferencia', max_length=100),
        ),
    ]
