# Generated by Django 5.2.8 on 2026-08-16 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0056_alter_cobrootrosingresos_forma_cobro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='factura',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='facturaotrosingresos',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='facturaotrosingresos',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
