# Generated by Django 5.2.1 on 2025-06-11 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0001_initial'),
        ('gastos', '0005_gasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gastos.grupogasto')),
                ('subgrupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gastos.subgrupogasto')),
                ('tipo_gasto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gastos.tipogasto')),
            ],
            options={
                'unique_together': {('empresa', 'grupo', 'subgrupo', 'tipo_gasto', 'anio', 'mes')},
            },
        ),
    ]
