# Generated by Django 5.2.1 on 2025-07-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('presupuestos', '0003_presupuestoingreso'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='presupuestoingreso',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='presupuestoingreso',
            name='tipo_otro',
            field=models.CharField(blank=True, choices=[('estacionamiento', 'Estacionamiento'), ('sanitario', 'Sanitarios'), ('propineros', 'Propineros'), ('publicidad', 'Publicidad'), ('servicios', 'Servicios'), ('otros', 'Otros')], help_text="Solo se usa si origen='otros'", max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='presupuestoingreso',
            unique_together={('empresa', 'anio', 'mes', 'origen', 'tipo_otro')},
        ),
    ]
