# Generated by Django 5.2.1 on 2025-07-12 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0004_alter_presupuestoingreso_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoingreso',
            name='tipo_otro',
            field=models.CharField(blank=True, help_text="Solo se usa si origen='otros'", max_length=20, null=True),
        ),
    ]
