# Generated by Django 5.2.1 on 2025-07-12 23:32

import facturacion.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('presupuestos', '0005_alter_presupuestoingreso_tipo_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoingreso',
            name='tipo_otro',
            field=models.CharField(blank=True, help_text="Solo se usa si origen='otros'", null=True, verbose_name=facturacion.models.TipoOtroIngreso),
        ),
    ]
