# Generated by Django 5.2.1 on 2025-07-12 23:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0033_alter_tipootroingreso_nombre'),
        ('presupuestos', '0006_alter_presupuestoingreso_tipo_otro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestoingreso',
            name='tipo_otro',
            field=models.ForeignKey(blank=True, help_text="Solo se usa si origen='otros'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.tipootroingreso'),
        ),
    ]
