# Generated by Django 5.2.1 on 2025-09-24 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_rfc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('falta', 'Falta'), ('retardo', 'Retardo'), ('extra', 'Hora Extra'), ('permiso', 'Permiso'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('dias festivos', 'Festivos trabajados'), ('descanso', 'Descansos trabajados'), ('otro', 'Otro')], max_length=20)),
                ('fecha', models.DateField(help_text='Fecha de la incidencia (o inicio del periodo)')),
                ('fecha_fin', models.DateField(blank=True, help_text='Solo si aplica periodo (vacaciones, incapacidad, etc.)', null=True)),
                ('dias', models.PositiveIntegerField(default=1, help_text='Cantidad de días de la incidencia')),
                ('descripcion', models.TextField(blank=True)),
                ('numero_incapacidad_imss', models.CharField(blank=True, help_text="Capturar solo si el tipo de incidencia es 'Incapacidad'", max_length=30, null=True, verbose_name='Número de incapacidad IMSS')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.empleado')),
            ],
        ),
    ]
