# Generated by Django 5.2.1 on 2025-10-24 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_incidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidencia',
            name='tipo',
            field=models.CharField(choices=[('falta', 'Falta'), ('retardo', 'Retardo'), ('extra', 'Hora Extra'), ('permiso', 'Permiso'), ('vacaciones', 'Vacaciones'), ('incapacidad', 'Incapacidad'), ('dias festivos', 'Festivos trabajados'), ('descanso', 'Descansos trabajados'), ('descuento', 'Descuento'), ('devolucion', 'Devolución'), ('otro', 'Otro')], max_length=20),
        ),
    ]
