# Generated by Django 5.2.1 on 2025-10-24 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0004_alter_incidencia_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='importe',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Solo si aplica descuento o devolución', max_digits=10, null=True),
        ),
    ]
