# Generated by Django 5.2.8 on 2026-07-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0008_token_asistencia_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='horario_bloqueado',
            field=models.BooleanField(default=False, help_text='Una vez editado el horario esperado, solo un superusuario puede volver a modificarlo.'),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='hora_entrada',
            field=models.DateTimeField(blank=True, help_text='Hora esperada de entrada, ej. 08:00', null=True),
        ),
        migrations.AlterField(
            model_name='registroasistencia',
            name='hora_salida',
            field=models.DateTimeField(blank=True, help_text='Hora esperada de salida, ej. 17:00', null=True),
        ),
    ]
