# Generated by Django 5.2.8 on 2026-07-24 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0009_registroasistencia_horario_bloqueado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registroasistencia',
            name='horario_bloqueado',
        ),
        migrations.AddField(
            model_name='empleado',
            name='horario_bloqueado',
            field=models.BooleanField(default=False, help_text='Una vez editado el horario esperado, solo un superusuario puede volver a modificarlo.'),
        ),
    ]
