# Generated by Django 5.2.8 on 2026-07-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0010_remove_registroasistencia_horario_bloqueado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registroasistencia',
            name='dentro_de_rango_fin_comida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='dentro_de_rango_inicio_comida',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='distancia_metros_fin_comida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='distancia_metros_inicio_comida',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='hora_fin_comida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='hora_inicio_comida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='lat_fin_comida',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='lat_inicio_comida',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='lng_fin_comida',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='lng_inicio_comida',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
