# Generated by Django 5.2.8 on 2026-07-25 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0011_registroasistencia_dentro_de_rango_fin_comida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UbicacionEnVivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('distancia_metros', models.FloatField(blank=True, null=True)),
                ('dentro_de_zona', models.BooleanField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_en_vivo', to='empleados.empleado')),
            ],
        ),
    ]
