# Generated by Django 5.2.8 on 2026-07-25 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0012_ubicacionenvivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacionenvivo',
            name='empleado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_en_vivo_rel', to='empleados.empleado'),
        ),
    ]
