# Generated by Django 5.2.8 on 2026-08-21 23:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0013_alter_ubicacionenvivo_empleado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_solicitud', models.DateField(default=django.utils.timezone.now)),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto total solicitado', max_digits=10)),
                ('motivo', models.TextField(blank=True)),
                ('numero_parcialidades', models.PositiveIntegerField(default=1, help_text='Número de descuentos en los que se pagará')),
                ('monto_parcialidad', models.DecimalField(blank=True, decimal_places=2, help_text='Se calcula automático (monto / parcialidades) si se deja en blanco', max_digits=10, null=True)),
                ('fecha_primer_descuento', models.DateField(blank=True, null=True)),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de autorización'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('liquidada', 'Liquidada')], default='pendiente', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_prestamo', to='empleados.empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
