# Generated by Django 5.2.8 on 2026-03-07 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0008_alter_empresa_saldo_final'),
        ('facturacion', '0046_factura_factura_global'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=20)),
                ('archivo', models.FileField(upload_to='estados_cuenta/')),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=10)),
                ('identificado', models.BooleanField(default=False)),
                ('deposito_por_identificar', models.BooleanField(default=False)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='conciliaciones.estadocuenta')),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.factura')),
            ],
        ),
    ]
