# Generated by Django 5.2.8 on 2026-05-15 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0001_initial'),
        ('empresas', '0012_alter_cuentabancaria_banco'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientobancario',
            name='estado_cuenta',
        ),
        migrations.RemoveField(
            model_name='movimientobancario',
            name='factura',
        ),
        migrations.CreateModel(
            name='EstadoCuentaBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='estados_cuenta/')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_conciliacion', models.DateTimeField(auto_now_add=True)),
                ('resumen', models.JSONField()),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conciliaciones.estadocuentabancario')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoEstadoCuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('estado_cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='conciliaciones.estadocuentabancario')),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=255)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('tipo', models.CharField(choices=[('cargo', 'Cargo'), ('abono', 'Abono')], max_length=10)),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('conciliado', models.BooleanField(default=False)),
                ('origen', models.CharField(max_length=50)),
                ('cuenta_bancaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('movimiento_estado_cuenta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliaciones.movimientoestadocuenta')),
            ],
        ),
        migrations.AddField(
            model_name='movimientoestadocuenta',
            name='movimiento_sistema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conciliaciones.movimientosistema'),
        ),
        migrations.DeleteModel(
            name='EstadoCuenta',
        ),
        migrations.DeleteModel(
            name='MovimientoBancario',
        ),
    ]
