# Generated by Django 5.2.8 on 2026-07-10 22:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0002_remove_movimientobancario_estado_cuenta_and_more'),
        ('empresas', '0019_remove_empresa_es_demo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoCuentaPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_final', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo_calculado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cerrado', models.BooleanField(default=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_periodo', to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_periodo', to='empresas.empresa')),
            ],
            options={
                'verbose_name': 'Saldo por período',
                'verbose_name_plural': 'Saldos por período',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('cuenta', 'anio', 'mes')},
            },
        ),
    ]
