# Generated by Django 5.2.8 on 2026-05-15 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0002_remove_movimientobancario_estado_cuenta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estadocuentabancario',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estadocuentabancario',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
