# Generated by Django 5.2.8 on 2026-07-12 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conciliaciones', '0003_saldocuentaperiodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='saldocuentaperiodo',
            name='abonos_banco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='saldocuentaperiodo',
            name='cargos_banco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
