# Generated by Django 5.2.8 on 2026-07-03 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0014_alter_empresa_cuenta_bancaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CorteEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('semanal', 'Semanal'), ('quincenal', 'Quincenal'), ('mensual', 'Mensual')], default='mensual', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('total_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_boletos', models.PositiveIntegerField(default=0)),
                ('tiene_operador_externo', models.BooleanField(default=False)),
                ('nombre_operador', models.CharField(blank=True, max_length=100, null=True)),
                ('porcentaje_operador', models.DecimalField(decimal_places=2, default=0, help_text='% que corresponde al operador. 0 si es 100% de la plaza.', max_digits=5)),
                ('monto_renta_operador', models.DecimalField(decimal_places=2, default=0, help_text='Renta fija que paga el operador, si aplica.', max_digits=12)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('archivo_origen', models.FileField(blank=True, null=True, upload_to='estacionamiento/')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('cuenta_bancaria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='empresas.cuentabancaria')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='TicketEstacionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ticket', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField()),
                ('minutos', models.PositiveIntegerField(default=0)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta')], max_length=20)),
                ('corte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='estacionamiento.corteestacionamiento')),
            ],
            options={
                'ordering': ['fecha', 'hora_salida'],
            },
        ),
    ]
