# Generated by Django 5.2.8 on 2026-07-04 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_alter_empresa_cuenta_bancaria'),
        ('estacionamiento', '0001_initial'),
        ('facturacion', '0049_alter_facturaotrosingresos_observaciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='corteestacionamiento',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Corte de estacionamiento', 'verbose_name_plural': 'Cortes de estacionamiento'},
        ),
        migrations.AddField(
            model_name='corteestacionamiento',
            name='factura',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='corte_estacionamiento', to='facturacion.facturaotrosingresos'),
        ),
        migrations.AlterField(
            model_name='corteestacionamiento',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cortes_estacionamiento', to='empresas.cuentabancaria'),
        ),
    ]
