# Generated by Django 5.2.8 on 2026-07-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0002_alter_corteestacionamiento_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='corteestacionamiento',
            name='fecha_deposito',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de depósito en banco'),
        ),
    ]
