# Generated by Django 5.2.8 on 2026-08-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0003_corteestacionamiento_fecha_deposito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corteestacionamiento',
            name='porcentaje_operador',
        ),
        migrations.AlterField(
            model_name='corteestacionamiento',
            name='monto_renta_operador',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Renta fija mensual que paga el operador externo.', max_digits=12),
        ),
    ]
