# Generated by Django 5.2.8 on 2026-08-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estacionamiento', '0004_remove_corteestacionamiento_porcentaje_operador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corteestacionamiento',
            name='cuenta_bancaria',
        ),
        migrations.RemoveField(
            model_name='corteestacionamiento',
            name='fecha_deposito',
        ),
    ]
