# Generated by Django 5.2.8 on 2026-09-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones_sistema', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionsistema',
            name='dispara_tour',
            field=models.BooleanField(default=False, help_text='Si al hacer clic en esta notificación, también debe iniciar el tour guiado del sistema.'),
        ),
    ]
