# Generated by Django 5.2.8 on 2026-09-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones_sistema', '0002_notificacionsistema_dispara_tour'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificacionsistema',
            name='dispara_tour',
        ),
        migrations.AddField(
            model_name='notificacionsistema',
            name='tour_a_disparar',
            field=models.CharField(blank=True, choices=[('navbar', 'Recorrido del menú principal'), ('facturacion', 'Recorrido de Facturación'), ('gastos', 'Recorrido de Gastos'), ('cartera', 'Recorrido de Cartera Vencida')], help_text='Si al hacer clic en esta notificación, también debe iniciar un tour guiado específico. Déjalo vacío si no aplica.', max_length=30, null=True),
        ),
    ]
