# Generated by Django 5.2.8 on 2026-09-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones_sistema', '0003_remove_notificacionsistema_dispara_tour_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacionsistema',
            name='tour_a_disparar',
            field=models.CharField(blank=True, choices=[('navbar', 'Recorrido del menú principal'), ('facturacion', 'Recorrido de Facturación'), ('gastos', 'Recorrido de Gastos'), ('cartera', 'Recorrido de Cartera Vencida'), ('lista_areas', 'Lista de Áreas'), ('historial_contratos', 'Historial de Contratos'), ('expediente_contratos', 'Expediente de Contratos')], help_text='Si al hacer clic en esta notificación, también debe iniciar un tour guiado específico. Déjalo vacío si no aplica.', max_length=30, null=True),
        ),
    ]
