# Generated by Django 5.2.8 on 2026-09-22 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones_sistema', '0004_alter_notificacionsistema_tour_a_disparar'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacionsistema',
            name='segmento_objetivo',
            field=models.CharField(blank=True, choices=[('', 'Solo GESAC (comercial/habitacional) -- default'), ('escuela', 'Solo Escuela'), ('todos', 'Todos los segmentos')], default='', help_text='A qué tipo de cliente le llega este aviso. Vacío = solo GESAC.', max_length=20),
        ),
    ]
