# Generated by Django 5.2.8 on 2026-07-04 20:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresas', '0014_alter_empresa_cuenta_bancaria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('administradora', 'Empresa Administradora'), ('comite', 'Comité / Mesa Directiva')], max_length=20)),
                ('plan', models.CharField(choices=[('basico', 'Básico — 1 empresa — $299/mes'), ('profesional', 'Profesional — hasta 3 empresas — $699/mes'), ('enterprise', 'Enterprise — ilimitadas — $1,499/mes')], default='basico', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('activo', models.BooleanField(default=False)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('nombre_organizacion', models.CharField(blank=True, help_text='Nombre de la empresa administradora o del comité', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_acceso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario de acceso',
                'verbose_name_plural': 'Usuarios de acceso',
            },
        ),
        migrations.CreateModel(
            name='AccesoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('suspendido', 'Suspendido')], default='pendiente', max_length=20)),
                ('aprobado', models.BooleanField(default=False)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('ver_dashboard', models.BooleanField(default=False)),
                ('ver_estado_resultados', models.BooleanField(default=False)),
                ('ver_cobranza', models.BooleanField(default=False)),
                ('ver_gastos', models.BooleanField(default=False)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_usuarios', to='empresas.empresa')),
                ('usuario_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesos_empresas', to='acceso_empresas.usuarioacceso')),
            ],
            options={
                'verbose_name': 'Acceso a empresa',
                'verbose_name_plural': 'Accesos a empresas',
                'unique_together': {('usuario_acceso', 'empresa')},
            },
        ),
    ]
