# Generated by Django 5.2.8 on 2026-07-07 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarioacceso',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='usuarioacceso',
            name='reset_token_expira',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
