# Generated by Django 5.2.8 on 2026-08-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoempresa',
            name='gestion_cobranza',
            field=models.BooleanField(default=False),
        ),
    ]
