# Generated by Django 5.2.8 on 2026-08-26 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_empresas', '0002_accesoempresa_gestion_cobranza'),
        ('empresas', '0032_empresa_umbral_alerta_gastos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaGesac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.CharField(max_length=255)),
                ('gasto_id', models.PositiveIntegerField(blank=True, null=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_usuarios', to='empresas.empresa')),
                ('usuario_acceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='acceso_empresas.usuarioacceso')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
