# Generated by Django 5.2.8 on 2026-09-03 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_empresas', '0003_alertagesac'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesoempresa',
            name='recibir_alertas_gastos',
            field=models.BooleanField(default=False, help_text='Si este usuario recibe una alerta cuando se registre un gasto/solicitud de más de $50,000 en esta empresa.'),
        ),
    ]
