# Generated by Django 5.2.8 on 2025-11-27 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='anuncios/logos/')),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='anuncios/imagenes/')),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('link_pagina', models.URLField(blank=True)),
                ('link_facebook', models.URLField(blank=True)),
                ('link_instagram', models.URLField(blank=True)),
                ('link_otro', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
