# Generated by Django 5.2.1 on 2025-10-09 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', 'General de Ley Personas Morales'), ('603', 'Personas Morales con Fines no Lucrativos'), ('605', 'Sueldos y Salarios e Ingresos Asimilados a Salarios'), ('606', 'Arrendamiento'), ('612', 'Personas Físicas con Actividades Empresariales y Profesionales'), ('616', 'Sin obligaciones fiscales'), ('621', 'Incorporación Fiscal'), ('626', 'Régimen Simplificado de Confianza')], max_length=100, null=True),
        ),
    ]
