# Generated by Django 5.2.1 on 2025-10-09 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_cliente_codigo_postal_cliente_regimen_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='uso_cfdi',
            field=models.CharField(choices=[('G03', 'Gastos en general'), ('S01', 'Sin efectos fiscales')], default='G03', max_length=100),
        ),
    ]
