# Generated by Django 5.2.1 on 2025-11-02 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_cliente_uso_cfdi'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='tipo_contribuyente',
            field=models.CharField(blank=True, choices=[('fisica', 'Persona Física'), ('moral', 'Persona Moral')], max_length=100, null=True),
        ),
    ]
