# Generated by Django 5.2.1 on 2025-11-03 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_tipo_contribuyente'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='direccion_domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_contribuyente',
            field=models.CharField(blank=True, choices=[('Fisica', 'Persona Física'), ('Moral', 'Persona Moral'), ('Publico general', 'Público en General')], max_length=100, null=True),
        ),
    ]
