# Generated by Django 5.2.1 on 2025-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_cliente_direccion_domicilio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='direccion_domicilio',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
