# Generated by Django 5.2.8 on 2026-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_alter_cliente_direccion_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='factura_global',
            field=models.BooleanField(default=False),
        ),
    ]
