# Generated by Django 5.2.8 on 2026-03-09 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0008_cliente_factura_global'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='referencia_pago',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
