# Generated by Django 5.2.8 on 2026-07-24 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0009_cliente_referencia_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='referencia_pago',
        ),
    ]
