# Generated by Django 5.2.8 on 2026-08-07 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_remove_cliente_referencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='objeto_impuesto',
            field=models.CharField(choices=[('01', 'No objeto de impuesto'), ('02', 'Sí objeto de impuesto'), ('03', 'Sí objeto de impuesto y no obligado al desglose')], default='02', help_text='Objeto de impuesto (IVA) que se usará por default al timbrar sus facturas.', max_length=2),
        ),
    ]
