# Generated by Django 5.2.1 on 2025-08-27 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_alter_empleado_rfc'),
        ('principal', '0010_perfilusuario_mostrar_wizard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto')], default='pendiente', max_length=20)),
                ('solucion', models.TextField(blank=True, null=True)),
                ('fecha_solucion', models.DateTimeField(blank=True, null=True)),
                ('empleado_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_asignados', to='empleados.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField()),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='principal.ticketmantenimiento')),
            ],
        ),
    ]
