# Generated by Django 5.2.1 on 2025-09-26 04:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0019_alter_areacomun_tipo_area'),
        ('locales', '0011_localcomercial_giro'),
        ('principal', '0011_ticketmantenimiento_seguimientoticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.areacomun')),
                ('local', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='locales.localcomercial')),
            ],
        ),
    ]
