# Generated by Django 5.2.1 on 2025-09-26 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0019_alter_areacomun_tipo_area'),
        ('locales', '0011_localcomercial_giro'),
        ('principal', '0012_visitanteacceso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitanteacceso',
            name='area',
        ),
        migrations.RemoveField(
            model_name='visitanteacceso',
            name='local',
        ),
        migrations.AddField(
            model_name='visitanteacceso',
            name='areas',
            field=models.ManyToManyField(blank=True, to='areas.areacomun', verbose_name='Áreas comunes'),
        ),
        migrations.AddField(
            model_name='visitanteacceso',
            name='locales',
            field=models.ManyToManyField(blank=True, to='locales.localcomercial', verbose_name='Locales'),
        ),
    ]
