# Generated by Django 5.2.1 on 2025-09-26 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_cuenta_bancaria'),
        ('principal', '0013_remove_visitanteacceso_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
            preserve_default=False,
        ),
    ]
