# Generated by Django 5.2.1 on 2025-10-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0015_temageneral_votacioncorreo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacioncorreo',
            name='voto',
            field=models.CharField(choices=[('si', 'Sí'), ('no', 'No'), ('abstencion', 'Abstención'), (None, 'Pendiente')], default=None, max_length=20),
        ),
    ]
