# Generated by Django 5.2.1 on 2025-10-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0017_alter_votacioncorreo_voto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votacioncorreo',
            name='voto',
            field=models.CharField(blank=True, choices=[('si', 'Sí'), ('no', 'No'), ('abstencion', 'Abstención')], max_length=20, null=True),
        ),
    ]
