# Generated by Django 5.2.1 on 2025-10-04 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_stripe_public_key_empresa_stripe_secret_key_and_more'),
        ('principal', '0018_alter_votacioncorreo_voto'),
    ]

    operations = [
        migrations.AddField(
            model_name='temageneral',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
