# Generated by Django 5.2.1 on 2025-10-04 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_stripe_public_key_empresa_stripe_secret_key_and_more'),
        ('principal', '0019_temageneral_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temageneral',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
