# Generated by Django 5.2.1 on 2025-11-04 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0021_estadocuentaarchivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EstadoCuentaArchivo',
        ),
    ]
