# Generated by Django 5.2.1 on 2025-11-06 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0022_delete_estadocuentaarchivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitanteToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=40, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('visitante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='principal.visitanteacceso')),
            ],
        ),
    ]
