# Generated by Django 5.2.8 on 2025-11-18 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0023_visitantetoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='acceso_api_reporte',
            field=models.BooleanField(default=False),
        ),
    ]
