# Generated by Django 5.2.8 on 2025-11-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0025_aviso'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
