# Generated by Django 5.2.8 on 2025-11-25 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0026_visitanteacceso_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de registro'),
        ),
    ]
