# Generated by Django 5.2.8 on 2025-11-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0027_visitanteacceso_fecha_registro'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
    ]
