# Generated by Django 5.2.8 on 2025-11-28 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0028_visitanteacceso_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='es_admin',
            field=models.BooleanField(default=False, verbose_name='Es administrador'),
        ),
    ]
