# Generated by Django 5.2.8 on 2025-12-02 08:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_es_plus'),
        ('principal', '0029_visitanteacceso_es_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
