# Generated by Django 5.2.8 on 2025-12-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_es_plus'),
        ('principal', '0030_aviso_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aviso',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
    ]
