# Generated by Django 5.2.8 on 2025-12-10 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_es_plus'),
        ('principal', '0031_alter_aviso_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitanteacceso',
            name='empresa',
        ),
        migrations.AddField(
            model_name='visitanteacceso',
            name='empresas',
            field=models.ManyToManyField(to='empresas.empresa'),
        ),
    ]
