# Generated by Django 5.2.8 on 2026-01-08 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0032_remove_visitanteacceso_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre Completo'),
        ),
    ]
