# Generated by Django 5.2.8 on 2026-02-05 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0033_visitanteacceso_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='membresia_tipo',
            field=models.CharField(choices=[('basica', 'Básica'), ('plus', 'Plus'), ('premium', 'Premium')], default='basica', max_length=20, verbose_name='Tipo de membresía'),
        ),
    ]
