# Generated by Django 5.2.8 on 2026-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0034_visitanteacceso_membresia_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MejoraSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_visita_changelog',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
