# Generated by Django 5.2.8 on 2026-05-14 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0035_mejorasistema_perfilusuario_ultima_visita_changelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MejoraSistema',
        ),
    ]
