# Generated by Django 5.2.8 on 2026-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0036_delete_mejorasistema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('demo', 'Demo'), ('plus', 'Plus'), ('premium', 'Premium'), ('gratis', 'Gratis')], default='demo', max_length=20),
        ),
    ]
