# Generated by Django 5.2.8 on 2026-06-18 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0037_alter_perfilusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='stripe_plus_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='stripe_premium_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
