# Generated by Django 5.2.8 on 2026-07-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0038_perfilusuario_stripe_plus_subscription_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
