# Generated by Django 5.2.8 on 2026-07-28 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acceso_empresas', '0001_initial'),
        ('principal', '0039_perfilusuario_fecha_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitanteacceso',
            name='usuario_acceso_origen',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitante_vinculado', to='acceso_empresas.usuarioacceso'),
        ),
    ]
