# Generated by Django 5.2.8 on 2026-08-03 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0040_visitanteacceso_usuario_acceso_origen'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='es_contador',
            field=models.BooleanField(default=False, help_text='Si está activo, este usuario solo ve el menú reducido de reportes contables al iniciar sesión.'),
        ),
    ]
