# Generated by Django 5.2.8 on 2026-08-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0041_perfilusuario_es_contador'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si está activo, se le fuerza a cambiar su contraseña en el próximo inicio de sesión.'),
        ),
    ]
