# Generated by Django 5.2.8 on 2026-08-03 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0023_empresa_estado'),
        ('principal', '0042_perfilusuario_debe_cambiar_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='empresas_contador',
            field=models.ManyToManyField(blank=True, help_text='Empresas a las que este contador tiene acceso (solo aplica si es_contador=True).', related_name='contadores', to='empresas.empresa'),
        ),
    ]
