# Generated by Django 5.2.8 on 2026-08-28 04:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0043_perfilusuario_empresas_contador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMembresiaTransferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_solicitado', models.CharField(choices=[('plus', 'Plus'), ('premium', 'Premium')], max_length=20)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('meses_cubiertos', models.PositiveIntegerField(default=1, help_text='Cuántos meses de membresía cubre este pago.')),
                ('fecha_transferencia', models.DateField(help_text='Fecha en que el cliente dice haber hecho la transferencia.')),
                ('referencia', models.CharField(blank=True, help_text='Número de referencia o folio de la transferencia, si lo tienen.', max_length=100, null=True)),
                ('comprobante', models.FileField(upload_to='comprobantes_membresia/')),
                ('estatus', models.CharField(choices=[('pendiente', 'Pendiente de revisión'), ('confirmado', 'Confirmado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_rechazo', models.CharField(blank=True, max_length=255, null=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_membresia_confirmados', to=settings.AUTH_USER_MODEL)),
                ('perfil_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_transferencia', to='principal.perfilusuario')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
