# Generated by Django 5.2.8 on 2026-08-28 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0044_pagomembresiatransferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMembresia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(help_text='Ej. BBVA, Santander, etc.', max_length=100)),
                ('titular', models.CharField(help_text='A nombre de quién está la cuenta.', max_length=150)),
                ('clabe', models.CharField(blank=True, help_text='CLABE interbancaria (18 dígitos).', max_length=18, null=True)),
                ('numero_cuenta', models.CharField(blank=True, help_text='Número de cuenta, si aplica además de la CLABE.', max_length=30, null=True)),
                ('precio_plus', models.DecimalField(decimal_places=2, help_text='Precio mensual fijo del plan Plus.', max_digits=10)),
                ('precio_premium', models.DecimalField(decimal_places=2, help_text='Precio mensual fijo del plan Premium.', max_digits=10)),
            ],
            options={
                'verbose_name': 'Configuración de Membresía',
                'verbose_name_plural': 'Configuración de Membresía',
            },
        ),
    ]
