# Generated by Django 5.2.8 on 2026-09-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0045_configuracionmembresia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='ha_visto_tour_inicial',
            field=models.BooleanField(default=False, help_text='Si ya vio el recorrido guiado de bienvenida al sistema.'),
        ),
    ]
