# Generated by Django 5.2.8 on 2026-09-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0046_perfilusuario_ha_visto_tour_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionmembresia',
            name='precio_plus_escuela',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mensual fijo del plan Plus para el ERP Escolar.', max_digits=10, null=True),
        ),
    ]
