# Generated by Django 5.2.8 on 2026-07-08 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acceso_empresas', '0001_initial'),
        ('empresas', '0014_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencion', models.CharField(blank=True, choices=[('crear_cliente', 'Crear Cliente'), ('crear_proveedor', 'Crear Proveedor'), ('actualizar_cliente', 'Actualizar Cliente'), ('actualizar_proveedor', 'Actualizar Proveedor'), ('listar_clientes', 'Listar Clientes'), ('listar_proveedores', 'Listar Proveedores'), ('otro', 'Otro')], max_length=50, null=True)),
                ('estado', models.CharField(choices=[('iniciada', 'Iniciada'), ('solicitando_datos', 'Solicitando Datos'), ('validando', 'Validando'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='iniciada', max_length=50)),
                ('datos_recopilados', models.JSONField(blank=True, default=dict)),
                ('errores', models.JSONField(blank=True, default=dict)),
                ('mensajes', models.JSONField(blank=True, default=list)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresas.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_asistente', to='acceso_empresas.usuarioacceso')),
            ],
            options={
                'verbose_name': 'Conversación Asistente',
                'verbose_name_plural': 'Conversaciones Asistente',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('usuario', 'Usuario'), ('asistente', 'Asistente')], max_length=20)),
                ('contenido', models.TextField()),
                ('opciones', models.JSONField(blank=True, default=list)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_historial', to='asistente_premium.conversacionasistente')),
            ],
            options={
                'verbose_name': 'Mensaje Asistente',
                'verbose_name_plural': 'Mensajes Asistente',
                'ordering': ['fecha_creacion'],
            },
        ),
    ]
