# Generated by Django 5.2.8 on 2026-07-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente_premium', '0002_alter_conversacionasistente_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversacionasistente',
            name='campo_actual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
