# Generated by Django 5.2.8 on 2026-08-13 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistente_premium', '0003_conversacionasistente_campo_actual'),
        ('empresas', '0028_empresa_precio_toalla'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsoConsultaManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('contador', models.PositiveIntegerField(default=0)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos_consulta_manual', to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'fecha')},
            },
        ),
    ]
