# Generated by Django 5.2.1 on 2025-08-05 00:17

from django.db import migrations, models

def vaciar_rfc_a_null(apps, schema_editor):
    Proveedor = apps.get_model('proveedores', 'Proveedor')
    Proveedor.objects.filter(rfc='').update(rfc=None)

class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.RunPython(vaciar_rfc_a_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(max_length=13, blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'rfc')},
        ),
    ]
