# Generated by Django 5.2.1 on 2025-11-01 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_alter_proveedor_rfc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='repse_estatus',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='repse_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
