# Generated by Django 5.2.1 on 2025-11-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_proveedor_repse_estatus_proveedor_repse_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='repse_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
