# Generated by Django 5.2.1 on 2025-11-01 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_proveedor_repse_vigencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='repse_estatus',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='repse_numero',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='repse_vigencia',
        ),
    ]
