# Generated by Django 5.2.1 on 2025-11-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0007_remove_proveedor_repse_estatus_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='repse_numero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='repse_vigencia',
            field=models.DateField(blank=True, null=True),
        ),
    ]
