# Generated by Django 5.2.8 on 2026-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_remove_empresa_es_demo'),
        ('proveedores', '0008_proveedor_repse_numero_proveedor_repse_vigencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='proveedor',
            unique_together={('empresa', 'rfc')},
        ),
    ]
