# Generated by Django 5.2.1 on 2025-06-10 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0002_grupo_gasto_fijos'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubgrupoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subgrupos', to='gastos.grupogasto')),
            ],
            options={
                'verbose_name': 'Subgrupo de Gasto',
                'verbose_name_plural': 'Subgrupos de Gasto',
                'unique_together': {('grupo', 'nombre')},
            },
        ),
    ]
