# Generated by Django 5.2.8 on 2026-05-10 06:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_empresa_cuenta_bancaria'),
        ('gastos', '0003_alter_tipogasto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagogasto',
            name='cuenta_bancaria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos_gastos', to='empresas.cuentabancaria'),
        ),
    ]
