# Generated by Django 5.2.1 on 2025-06-10 22:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0003_subgrupogasto'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoGasto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('subgrupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tipos', to='gastos.subgrupogasto')),
            ],
        ),
    ]
