# Generated by Django 5.2.8 on 2026-07-22 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0004_pagogasto_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='folio_comprobante',
            field=models.CharField(blank=True, help_text='Folio o número de la factura/comprobante adjunto', max_length=100, null=True),
        ),
    ]
