# Generated by Django 5.2.1 on 2025-06-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0005_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='estatus',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='comprobante',
            field=models.FileField(blank=True, null=True, upload_to='comprobantes_gastos/'),
        ),
    ]
