# Generated by Django 5.2.8 on 2026-07-28 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_segmento'),
        ('gastos', '0005_gasto_folio_comprobante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=150)),
                ('naturaleza', models.CharField(choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], default='deudora', max_length=10)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcuentas', to='gastos.cuentacontable')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_contables', to='empresas.empresa')),
            ],
            options={
                'ordering': ['codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.AddField(
            model_name='tipogasto',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_gasto', to='gastos.cuentacontable'),
        ),
    ]
