# Generated by Django 5.2.8 on 2026-07-28 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_segmento'),
        ('gastos', '0006_cuentacontable_tipogasto_cuenta_contable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CargaCatalogoSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente_revision', 'Pendiente de revisión'), ('aplicada', 'Aplicada'), ('cancelada', 'Cancelada')], default='pendiente_revision', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CargaCatalogoFila',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fila_excel', models.PositiveIntegerField()),
                ('codigo', models.CharField(max_length=30)),
                ('nombre_cuenta', models.CharField(max_length=150)),
                ('codigo_padre', models.CharField(blank=True, max_length=30, null=True)),
                ('naturaleza', models.CharField(default='deudora', max_length=10)),
                ('grupo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('subgrupo_nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('similitud_pct', models.PositiveIntegerField(default=0)),
                ('accion', models.CharField(blank=True, choices=[('crear_nuevo', 'Crear nuevo tipo de gasto'), ('usar_existente', 'Usar tipo de gasto existente'), ('solo_cuenta', 'Solo cargar la cuenta (sin tipo de gasto)')], max_length=20, null=True)),
                ('tipo_gasto_elegido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gastos.tipogasto')),
                ('tipo_gasto_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='gastos.tipogasto')),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filas', to='gastos.cargacatalogosesion')),
            ],
            options={
                'ordering': ['fila_excel'],
            },
        ),
    ]
