# Generated by Django 5.2.8 on 2026-07-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_cargacatalogosesion_cargacatalogofila'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargacatalogofila',
            name='uso_especial',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
