# Generated by Django 5.2.1 on 2025-06-12 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0007_pagogasto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PagoGasto',
        ),
    ]
