# Generated by Django 5.2.8 on 2026-08-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0008_cargacatalogofila_uso_especial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupogasto',
            name='es_exento_iva',
            field=models.BooleanField(default=False, help_text='Actívalo para grupos como Nómina, donde los gastos NO incluyen IVA.'),
        ),
    ]
