# Generated by Django 5.2.8 on 2026-08-16 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_grupogasto_es_exento_iva'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='monto_base',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gasto',
            name='monto_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
