# Generated by Django 5.2.1 on 2025-06-12 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0009_pagogasto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagogasto',
            name='forma_pago',
            field=models.CharField(choices=[('transferencia', 'Transferencia'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta')], default='transferencia', max_length=30),
        ),
    ]
