# Generated by Django 5.2.1 on 2025-06-17 00:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0010_alter_pagogasto_forma_pago'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgrupogasto',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subgrupogasto',
            unique_together=set(),
        ),
    ]
