# Generated by Django 5.2.1 on 2025-06-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0011_alter_subgrupogasto_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='retencion_isr',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='gasto',
            name='retencion_iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
