# Generated by Django 5.2.1 on 2025-06-20 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0001_initial'),
        ('gastos', '0012_gasto_retencion_isr_gasto_retencion_iva'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgrupogasto',
            options={'verbose_name': 'Subgrupo de Gasto', 'verbose_name_plural': 'Subgrupos de Gasto'},
        ),
        migrations.AddField(
            model_name='grupogasto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='subgrupogasto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AddField(
            model_name='tipogasto',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='subgrupogasto',
            unique_together={('grupo', 'nombre')},
        ),
    ]
