# Generated by Django 5.2.1 on 2025-06-24 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0015_alter_gasto_empresa_alter_grupogasto_empresa_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subgrupogasto',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='subgrupogasto',
            unique_together=set(),
        ),
    ]
