# Generated by Django 5.2.1 on 2025-07-12 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gastos', '0017_pagogasto_comprobante_alter_gasto_comprobante'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupogasto',
            name='empresa',
        ),
        migrations.RemoveField(
            model_name='subgrupogasto',
            name='empresa',
        ),
    ]
