# Generated by Django 5.2.1 on 2025-10-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0003_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='stripe_public_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stripe_secret_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='stripe_webhook_secret',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
