# Generated by Django 5.2.1 on 2025-10-08 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0004_empresa_stripe_public_key_empresa_stripe_secret_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='regimen_fiscal',
            field=models.CharField(blank=True, choices=[('601', 'General de Ley Personas Morales'), ('603', 'Personas Morales con Fines no Lucrativos'), ('621', 'Incorporación Fiscal'), ('626', 'Régimen Simplificado de Confianza')], default='603', max_length=100, null=True),
        ),
    ]
