# Generated by Django 5.2.1 on 2025-10-09 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0005_empresa_regimen_fiscal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
