# Generated by Django 5.2.1 on 2025-10-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0006_empresa_codigo_postal'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='es_plus',
            field=models.BooleanField(default=False),
        ),
    ]
