# Generated by Django 5.2.8 on 2026-01-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0007_empresa_es_plus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='saldo_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=12, null=True),
        ),
    ]
