# Generated by Django 5.2.8 on 2026-03-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0008_alter_empresa_saldo_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='clabe',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
