# Generated by Django 5.2.8 on 2026-05-06 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0009_empresa_clabe'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('BANAMEX', 'Banamex'), ('BANCOMER', 'Bancomer'), ('SANTANDER', 'Santander'), ('HSBC', 'HSBC'), ('BBVA', 'BBVA'), ('IXE', 'Ixe'), ('SCOTIABANK', 'Scotiabank'), ('BANORTE', 'Banorte'), ('INBURSA', 'Inbursa'), ('BANCOPPEL', 'Bancoppel'), ('AFIRME', 'Afirme'), ('BAJIO', 'Bajío'), ('MULTIVA', 'Multiva'), ('BANREGIO', 'Banregio'), ('BANJERCITO', 'Banjército'), ('OTRO', 'Otro')], max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('clabe', models.CharField(blank=True, max_length=18, null=True)),
                ('moneda', models.CharField(blank=True, choices=[('MXN', 'Peso Mexicano'), ('USD', 'Dólar Estadounidense'), ('EUR', 'Euro'), ('GBP', 'Libra Esterlina'), ('JPY', 'Yen Japonés'), ('OTRO', 'Otro')], max_length=10, null=True)),
                ('tipo_cuenta', models.CharField(blank=True, choices=[('INVERSION', 'Inversión'), ('CORRIENTE', 'Corriente'), ('NOMINA', 'Nómina'), ('EMPRESARIAL', 'Empresarial'), ('OTRO', 'Otro')], max_length=100, null=True)),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('saldo_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas_bancarias', to='empresas.empresa')),
            ],
        ),
    ]
