# Generated by Django 5.2.8 on 2026-05-06 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0010_cuentabancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, choices=[('BANAMEX', 'Banamex'), ('BANCOMER', 'Bancomer'), ('SANTANDER', 'Santander'), ('HSBC', 'HSBC'), ('BBVA', 'BBVA'), ('IXE', 'Ixe'), ('SCOTIABANK', 'Scotiabank'), ('BANORTE', 'Banorte'), ('INBURSA', 'Inbursa'), ('BANCOPPEL', 'Bancoppel'), ('AFIRME', 'Afirme'), ('BAJIO', 'Bajío'), ('MULTIVA', 'Multiva'), ('BANREGIO', 'Banregio'), ('BANJERCITO', 'Banjército'), ('OTRO', 'Otro')], max_length=100, null=True),
        ),
    ]
