# Generated by Django 5.2.8 on 2026-05-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0011_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuentabancaria',
            name='banco',
            field=models.CharField(choices=[('BANAMEX', 'Banamex'), ('SANTANDER', 'Santander'), ('HSBC', 'HSBC'), ('BBVA', 'BBVA'), ('IXE', 'Ixe'), ('SCOTIABANK', 'Scotiabank'), ('BANORTE', 'Banorte'), ('INBURSA', 'Inbursa'), ('BANCOPPEL', 'Bancoppel'), ('AFIRME', 'Afirme'), ('BAJIO', 'Bajío'), ('MULTIVA', 'Multiva'), ('BANREGIO', 'Banregio'), ('BANJERCITO', 'Banjército'), ('OTRO', 'Otro')], max_length=100),
        ),
    ]
