# Generated by Django 5.2.8 on 2026-06-18 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0012_alter_cuentabancaria_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='es_premium',
            field=models.BooleanField(default=False),
        ),
    ]
