# Generated by Django 5.2.8 on 2026-07-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0013_empresa_es_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cuenta_bancaria',
            field=models.CharField(blank=True, choices=[('BANAMEX', 'Banamex'), ('SANTANDER', 'Santander'), ('HSBC', 'HSBC'), ('BBVA', 'BBVA'), ('IXE', 'Ixe'), ('SCOTIABANK', 'Scotiabank'), ('BANORTE', 'Banorte'), ('INBURSA', 'Inbursa'), ('BANCOPPEL', 'Bancoppel'), ('AFIRME', 'Afirme'), ('BAJIO', 'Bajío'), ('MULTIVA', 'Multiva'), ('BANREGIO', 'Banregio'), ('BANJERCITO', 'Banjército'), ('OTRO', 'Otro')], max_length=100, null=True),
        ),
    ]
