# Generated by Django 5.2.8 on 2026-07-09 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0014_alter_empresa_cuenta_bancaria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='clabe',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='cuenta_bancaria',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='numero_cuenta',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='saldo_final',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='saldo_inicial',
        ),
    ]
