# Generated by Django 5.2.8 on 2026-07-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0015_remove_empresa_clabe_remove_empresa_cuenta_bancaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='lat_oficina',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Latitud de la oficina/caseta donde se debe marcar asistencia', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='lng_oficina',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Longitud de la oficina/caseta donde se debe marcar asistencia', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='radio_permitido_metros',
            field=models.PositiveIntegerField(default=150, help_text='Radio permitido (en metros) alrededor de la ubicación para marcar asistencia válida'),
        ),
    ]
