# Generated by Django 5.2.8 on 2026-07-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0016_empresa_lat_oficina_empresa_lng_oficina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='lat_oficina',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Latitud de la oficina/caseta donde se debe marcar asistencia', max_digits=30, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='lng_oficina',
            field=models.DecimalField(blank=True, decimal_places=20, help_text='Longitud de la oficina/caseta donde se debe marcar asistencia', max_digits=30, null=True),
        ),
    ]
