# Generated by Django 5.2.8 on 2026-07-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0017_alter_empresa_lat_oficina_alter_empresa_lng_oficina'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='es_demo',
            field=models.BooleanField(default=True),
        ),
    ]
