# Generated by Django 5.2.8 on 2026-07-10 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0018_empresa_es_demo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='es_demo',
        ),
    ]
