# Generated by Django 5.2.8 on 2026-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0019_remove_empresa_es_demo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='radio_permitido_metros',
            field=models.PositiveIntegerField(default=50, help_text='Radio permitido (en metros) alrededor de la ubicación para marcar asistencia válida'),
        ),
    ]
