# Generated by Django 5.2.8 on 2026-07-28 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0020_alter_empresa_radio_permitido_metros'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='segmento',
            field=models.CharField(choices=[('comercial', 'Comercial (plaza / centro comercial)'), ('habitacional', 'Habitacional (condominio residencial)')], default='comercial', help_text='Determina la terminología y opciones que ve la empresa en el sistema (Local/Renta vs. Vivienda/Amenidad).', max_length=20),
        ),
    ]
