# Generated by Django 5.2.8 on 2026-07-28 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0021_empresa_segmento'),
        ('gastos', '0007_cargacatalogosesion_cargacatalogofila'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='cuenta_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuentas_bancarias', to='gastos.cuentacontable'),
        ),
    ]
