# Generated by Django 5.2.8 on 2026-08-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0022_cuentabancaria_cuenta_contable'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='estado',
            field=models.CharField(choices=[('activa', 'Activa'), ('prueba', 'En prueba'), ('suspendida', 'Suspendida'), ('cancelada', 'Cancelada'), ('gratis', 'Gratis')], default='activa', help_text='Controla si la empresa participa en procesos automáticos como la facturación mensual del Cron Job.', max_length=20),
        ),
    ]
