# Generated by Django 5.2.8 on 2026-08-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0023_empresa_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='precio_sanitario',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo por uso de sanitario. Déjalo vacío si tu condominio no cobra este servicio.', max_digits=6, null=True),
        ),
    ]
