# Generated by Django 5.2.8 on 2026-08-04 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0025_remove_cuentabancaria_precio_sanitario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='usa_boletos_fisicos_sanitario',
            field=models.BooleanField(default=False, help_text='Si está activo, el operador captura el número del boleto físico existente en vez de que el sistema genere un código aleatorio.'),
        ),
    ]
