# Generated by Django 5.2.8 on 2026-08-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0026_empresa_usa_boletos_fisicos_sanitario'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='precio_papel',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo por venta de papel. Déjalo vacío si no se vende por separado.', max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='usa_boletos_fisicos_papel',
            field=models.BooleanField(default=False),
        ),
    ]
