# Generated by Django 5.2.8 on 2026-08-08 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0027_empresa_precio_papel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='precio_toalla',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio fijo por toalla sanitaria. Déjalo vacío si no se vende.', max_digits=6, null=True),
        ),
    ]
