# Generated by Django 5.2.8 on 2026-08-19 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0028_empresa_precio_toalla'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twilio_sms_number',
            field=models.CharField(blank=True, help_text='Número de Twilio para SMS, formato +521234567890.', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='twilio_whatsapp_number',
            field=models.CharField(blank=True, help_text="Número de WhatsApp Business habilitado en Twilio, formato +521234567890 (sin 'whatsapp:').", max_length=20, null=True),
        ),
    ]
