# Generated by Django 5.2.8 on 2026-08-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0029_empresa_twilio_account_sid_empresa_twilio_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentabancaria',
            name='mostrar_en_referencia_pago',
            field=models.BooleanField(default=True, help_text='Si esta cuenta debe aparecer en el PDF de referencia de pago que recibe el cliente.'),
        ),
    ]
