# Generated by Django 5.2.8 on 2026-08-20 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0030_cuentabancaria_mostrar_en_referencia_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='absorber_comision_stripe',
            field=models.BooleanField(default=True, help_text='Si está activo, la empresa absorbe la comisión de Stripe -- el cliente paga exactamente el monto de la factura. Si está apagado, la comisión se le agrega al cliente por separado, y la empresa recibe el monto completo de la factura.'),
        ),
    ]
