# Generated by Django 5.2.8 on 2026-08-26 23:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0031_empresa_absorber_comision_stripe'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='umbral_alerta_gastos',
            field=models.DecimalField(decimal_places=2, default=Decimal('50000.00'), help_text='Monto a partir del cual se genera una alerta de gasto alto para los usuarios del portal con esa notificación activada.', max_digits=12),
        ),
    ]
