# Generated by Django 5.2.8 on 2026-09-15 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresas', '0032_empresa_umbral_alerta_gastos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='segmento',
            field=models.CharField(choices=[('comercial', 'Comercial (plaza / centro comercial)'), ('habitacional', 'Habitacional (condominio residencial)'), ('escolar', 'Escuela')], default='comercial', help_text='Determina la terminología y opciones que ve la empresa en el sistema (Local/Renta vs. Vivienda/Amenidad).', max_length=20),
        ),
    ]
