from django.urls import path

from principal.views import usuarios_demo

from . import views

urlpatterns = [
    path('nueva/', views.crear_factura, name='crear_factura'),
    path('lista/', views.lista_facturas, name='lista_facturas'),
    path('facturar-mes/', views.confirmar_facturacion, name='facturar_mes'),
    path('factura/<int:factura_id>/pago/', views.registrar_pago, name='registrar_pago'),
    path('pagos-origen/', views.pagos_por_origen, name='pagos_por_origen'),
    path('dashboard-saldos/', views.dashboard_saldos, name='dashboard_saldos'),
    path('dashboard-pagos/', views.dashboard_pagos, name='dashboard_pagos'),
    path('cartera/', views.cartera_vencida_saldos_antiguedad, name='cartera_vencida_saldos_antiguedad'),
    path('cartera/exportar/excel/', views.exportar_cartera_excel, name='exportar_cartera_excel'),
    path('pagos/exportar/excel/', views.exportar_pagos_excel, name='exportar_pagos_excel'),
    path('carga-masiva/', views.carga_masiva_facturas, name='carga_masiva_facturas'),
    path('plantilla-facturas/', views.plantilla_facturas_excel, name='plantilla_facturas_excel'),
    path('factura/<int:factura_id>/editar/', views.editar_factura, name='editar_factura'),
    #path('factura/exportar/excel/', views.exportar_lista_facturas_excel, name='exportar_lista_facturas_excel'),
    path('carga-masiva-c/', views.carga_masiva_facturas_cobradas, name='carga_masiva_facturas_cobradas'),
    path('detalle/<int:pk>/', views.facturas_detalle, name='facturas_detalle'),
    path('otros-ingresos/nueva/', views.crear_factura_otros_ingresos, name='crear_factura_otros_ingresos'),
    path('otros-ingresos/lista/', views.lista_facturas_otros_ingresos, name='lista_facturas_otros_ingresos'),
    path('otros-ingresos/factura/<int:factura_id>/cobro/', views.registrar_cobro_otros_ingresos, name='registrar_cobro_otros_ingresos'),
    path('facturas/otros-ingresos/factura/<int:factura_id>/detalle/', views.detalle_factura_otros_ingresos, name='detalle_factura_otros_ingresos'),
    path('otros-ingresos/reporte-cobros/', views.reporte_cobros_otros_ingresos, name='reporte_cobros_otros_ingresos'),
    path('otros-ingresos/reporte-cobros/exportar-excel/', views.exportar_cobros_otros_ingresos_excel, name='exportar_cobros_otros_ingresos_excel'),
    path('exportar_lista_facturas_otros_ingresos_excel/', views.exportar_lista_facturas_otros_ingresos_excel, name='exportar_lista_facturas_otros_ingresos_excel'),
    path('crear-tipo-ingreso/', views.crear_tipo_otro_ingreso, name='crear_tipo_otro_ingreso'),
    path('tipos-otro-ingreso-json/', views.tipos_otro_ingreso_json, name='tipos_otro_ingreso_json'),
    path('usuarios-demo/', usuarios_demo, name='usuarios_demo'),
    path('facturas/eliminar/<int:factura_id>/', views.eliminar_factura, name='eliminar_factura'),
    path('facturas-otros-ingresos/eliminar/<int:factura_id>/', views.eliminar_factura_otros_ingresos, name='eliminar_factura_otros_ingresos'),
    path('ingresos-mensuales/', views.grafico_ingresos_mensuales, name='grafico_ingresos_mensual'),
    path('ingresos-anuales/', views.grafico_ingresos_anual, name='grafico_ingresos_anual'),
    path('exportar-estado-cuenta/', views.exportar_estado_cuenta_excel, name='exportar_estado_cuenta_excel'),
    path('verificacion-facturacion/', views.verificacion_facturacion, name='verificacion_facturacion'),
    path('reportes/cartera-vencida/', views.reporte_cartera_vencida, name='reporte_cartera_vencida'),
    path('depositos-por-identificar/exportar/', views.exportar_depositos_por_identificar_excel, name='exportar_depositos_por_identificar_excel'),
    path('grupos-facturacion/', views.lista_grupos_facturacion, name='lista_grupos_facturacion'),
    path('grupos-facturacion/nuevo/', views.crear_grupo_facturacion, name='crear_grupo_facturacion'),
    path('grupos-facturacion/<int:grupo_id>/editar/', views.editar_grupo_facturacion, name='editar_grupo_facturacion'),
    path('saldos-a-favor/', views.lista_saldos_a_favor, name='lista_saldos_a_favor'),
    path('saldos-a-favor/nuevo/', views.registrar_saldo_a_favor, name='registrar_saldo_a_favor'),
    path('reportes/iva/', views.reporte_iva, name='reporte_iva'),
    path('reportes/iva/exportar/', views.exportar_reporte_iva_excel, name='exportar_reporte_iva_excel'),
    path('catalogo-cuentas/exportar-poliza-ingresos/', views.exportar_poliza_ingresos, name='exportar_poliza_ingresos'),
    path('catalogo-cuentas/homologar-cuotas/', views.homologar_tipos_cuota, name='homologar_tipos_cuota'),
    path('catalogo-cuentas/homologar-cuotas/<int:homologacion_id>/asignar/', views.asignar_cuenta_contable_cuota, name='asignar_cuenta_contable_cuota'),
    path('catalogo-cuentas/homologar-otros-ingresos/', views.homologar_tipos_otro_ingreso, name='homologar_tipos_otro_ingreso'),
    path('catalogo-cuentas/homologar-otros-ingresos/<int:tipo_id>/asignar/', views.asignar_cuenta_contable_otro_ingreso, name='asignar_cuenta_contable_otro_ingreso'),
]
