# Generated by Django 5.2.8 on 2026-07-28 03:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0010_remove_cliente_referencia_pago'),
        ('empresas', '0021_empresa_segmento'),
        ('facturacion', '0051_alter_pago_forma_pago'),
        ('locales', '0015_localcomercial_referencia_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_maxima', models.PositiveIntegerField(blank=True, null=True)),
                ('hora_apertura', models.TimeField(default='08:00')),
                ('hora_cierre', models.TimeField(default='22:00')),
                ('duracion_maxima_horas', models.PositiveIntegerField(default=4)),
                ('costo_reservacion', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('requiere_deposito', models.BooleanField(default=False)),
                ('monto_deposito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dias_anticipacion_minima', models.PositiveIntegerField(default=1)),
                ('activa', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenidades', to='empresas.empresa')),
            ],
            options={
                'unique_together': {('empresa', 'nombre')},
            },
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('numero_invitados', models.PositiveIntegerField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=255)),
                ('amenidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservaciones', to='amenidades.amenidad')),
                ('cancelado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservaciones_canceladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresas.empresa')),
                ('factura_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='facturacion.facturaotrosingresos')),
                ('propiedad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locales.localcomercial')),
                ('solicitado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
    ]
